// this file is automatically generated
// Copyright 2020 SourceGear
#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_unsafe)]
#![allow(unused_imports)]
#![allow(unused_parens)]

extern {
    fn __drop_handle(self_h : i64);
    fn __copy_handle(self_h : i64) -> i64;
}

// System
pub mod System {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Runtime
pub mod Runtime {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Runtime.CompilerServices
pub mod CompilerServices {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Runtime.CompilerServices.CompilerMarshalOverride
// from System.Runtime.CompilerServices.VisualC
pub struct CompilerMarshalOverride;
impl CompilerMarshalOverride {

}


// System.Runtime.CompilerServices.CppInlineNamespaceAttribute
// from System.Runtime.CompilerServices.VisualC
#[derive(Debug)]
pub struct CppInlineNamespaceAttribute {
    h : i64
}

impl ::sgrust_core::SGRustValue for CppInlineNamespaceAttribute {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_CompilerServices_CppInlineNamespaceAttribute_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_CompilerServices_CppInlineNamespaceAttribute_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for CppInlineNamespaceAttribute {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl CppInlineNamespaceAttribute {

    // .ctor(System.String)
    pub fn ctor__1__String(_dottedName : &::System_Runtime::System::String) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_CompilerServices_CppInlineNamespaceAttribute_ctor__1__String(thrown : *mut i64, _dottedName : i64) -> i64;
        }
        unsafe {
            let h = System_Runtime_CompilerServices_CppInlineNamespaceAttribute_ctor__1__String(&mut __thrown, _dottedName.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Attribute> for CppInlineNamespaceAttribute {
    fn into(self) -> ::System_Runtime::System::Attribute {
        unsafe { ::System_Runtime::System::Attribute::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for CppInlineNamespaceAttribute {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_CppInlineNamespaceAttribute_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Runtime::CompilerServices::CppInlineNamespaceAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_ctor_r_f<TA1> {
    fn ctor(p1 : TA1) -> Result<crate::System::Runtime::CompilerServices::CppInlineNamespaceAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_CppInlineNamespaceAttribute_ctor_1_f<TA1> {
    fn ctor_1(p1 : TA1) -> Result<crate::System::Runtime::CompilerServices::CppInlineNamespaceAttribute,::System_Runtime::System::Exception>;
}
impl System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_ctor_r_f<&::System_Runtime::System::String> for CppInlineNamespaceAttribute {
    fn ctor(p1 : &::System_Runtime::System::String) -> Result<crate::System::Runtime::CompilerServices::CppInlineNamespaceAttribute,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_CppInlineNamespaceAttribute_ctor_1_f<&::System_Runtime::System::String> for CppInlineNamespaceAttribute {
    fn ctor_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Runtime::CompilerServices::CppInlineNamespaceAttribute,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_CppInlineNamespaceAttribute_ctor_t_f<(&::System_Runtime::System::String,)> for CppInlineNamespaceAttribute {
    fn ctor(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Runtime::CompilerServices::CppInlineNamespaceAttribute,::System_Runtime::System::Exception> {
        Self::ctor__1__String(a.0,)
    }
}

// System.Runtime.CompilerServices.HasCopySemanticsAttribute
// from System.Runtime.CompilerServices.VisualC
#[derive(Debug)]
pub struct HasCopySemanticsAttribute {
    h : i64
}

impl ::sgrust_core::SGRustValue for HasCopySemanticsAttribute {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_CompilerServices_HasCopySemanticsAttribute_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_CompilerServices_HasCopySemanticsAttribute_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for HasCopySemanticsAttribute {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl HasCopySemanticsAttribute {

    // .ctor()
    pub fn ctor__0() -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_CompilerServices_HasCopySemanticsAttribute_ctor__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let h = System_Runtime_CompilerServices_HasCopySemanticsAttribute_ctor__0(&mut __thrown);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Attribute> for HasCopySemanticsAttribute {
    fn into(self) -> ::System_Runtime::System::Attribute {
        unsafe { ::System_Runtime::System::Attribute::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for HasCopySemanticsAttribute {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_HasCopySemanticsAttribute_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Runtime::CompilerServices::HasCopySemanticsAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_ctor_r_f<> {
    fn ctor() -> Result<crate::System::Runtime::CompilerServices::HasCopySemanticsAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_HasCopySemanticsAttribute_ctor_0_f<> {
    fn ctor_0() -> Result<crate::System::Runtime::CompilerServices::HasCopySemanticsAttribute,::System_Runtime::System::Exception>;
}
impl System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_ctor_r_f<> for HasCopySemanticsAttribute {
    fn ctor() -> Result<crate::System::Runtime::CompilerServices::HasCopySemanticsAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_HasCopySemanticsAttribute_ctor_0_f<> for HasCopySemanticsAttribute {
    fn ctor_0() -> Result<crate::System::Runtime::CompilerServices::HasCopySemanticsAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_HasCopySemanticsAttribute_ctor_t_f<()> for HasCopySemanticsAttribute {
    fn ctor(_a : ()) -> Result<crate::System::Runtime::CompilerServices::HasCopySemanticsAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}

// System.Runtime.CompilerServices.IsBoxed
// from System.Runtime.CompilerServices.VisualC
pub struct IsBoxed;
impl IsBoxed {

}


// System.Runtime.CompilerServices.IsByValue
// from System.Runtime.CompilerServices.VisualC
pub struct IsByValue;
impl IsByValue {

}


// System.Runtime.CompilerServices.IsCopyConstructed
// from System.Runtime.CompilerServices.VisualC
pub struct IsCopyConstructed;
impl IsCopyConstructed {

}


// System.Runtime.CompilerServices.IsExplicitlyDereferenced
// from System.Runtime.CompilerServices.VisualC
pub struct IsExplicitlyDereferenced;
impl IsExplicitlyDereferenced {

}


// System.Runtime.CompilerServices.IsImplicitlyDereferenced
// from System.Runtime.CompilerServices.VisualC
pub struct IsImplicitlyDereferenced;
impl IsImplicitlyDereferenced {

}


// System.Runtime.CompilerServices.IsJitIntrinsic
// from System.Runtime.CompilerServices.VisualC
pub struct IsJitIntrinsic;
impl IsJitIntrinsic {

}


// System.Runtime.CompilerServices.IsLong
// from System.Runtime.CompilerServices.VisualC
pub struct IsLong;
impl IsLong {

}


// System.Runtime.CompilerServices.IsPinned
// from System.Runtime.CompilerServices.VisualC
pub struct IsPinned;
impl IsPinned {

}


// System.Runtime.CompilerServices.IsSignUnspecifiedByte
// from System.Runtime.CompilerServices.VisualC
pub struct IsSignUnspecifiedByte;
impl IsSignUnspecifiedByte {

}


// System.Runtime.CompilerServices.IsUdtReturn
// from System.Runtime.CompilerServices.VisualC
pub struct IsUdtReturn;
impl IsUdtReturn {

}


// System.Runtime.CompilerServices.NativeCppClassAttribute
// from System.Runtime.CompilerServices.VisualC
#[derive(Debug)]
pub struct NativeCppClassAttribute {
    h : i64
}

impl ::sgrust_core::SGRustValue for NativeCppClassAttribute {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_CompilerServices_NativeCppClassAttribute_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_CompilerServices_NativeCppClassAttribute_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for NativeCppClassAttribute {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl NativeCppClassAttribute {

    // .ctor()
    pub fn ctor__0() -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_CompilerServices_NativeCppClassAttribute_ctor__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let h = System_Runtime_CompilerServices_NativeCppClassAttribute_ctor__0(&mut __thrown);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Attribute> for NativeCppClassAttribute {
    fn into(self) -> ::System_Runtime::System::Attribute {
        unsafe { ::System_Runtime::System::Attribute::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for NativeCppClassAttribute {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Runtime_CompilerServices_NativeCppClassAttribute_overload_NativeCppClassAttribute_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Runtime::CompilerServices::NativeCppClassAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_NativeCppClassAttribute_overload_ctor_r_f<> {
    fn ctor() -> Result<crate::System::Runtime::CompilerServices::NativeCppClassAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_NativeCppClassAttribute_overload_NativeCppClassAttribute_ctor_0_f<> {
    fn ctor_0() -> Result<crate::System::Runtime::CompilerServices::NativeCppClassAttribute,::System_Runtime::System::Exception>;
}
impl System_Runtime_CompilerServices_NativeCppClassAttribute_overload_ctor_r_f<> for NativeCppClassAttribute {
    fn ctor() -> Result<crate::System::Runtime::CompilerServices::NativeCppClassAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Runtime_CompilerServices_NativeCppClassAttribute_overload_NativeCppClassAttribute_ctor_0_f<> for NativeCppClassAttribute {
    fn ctor_0() -> Result<crate::System::Runtime::CompilerServices::NativeCppClassAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Runtime_CompilerServices_NativeCppClassAttribute_overload_NativeCppClassAttribute_ctor_t_f<()> for NativeCppClassAttribute {
    fn ctor(_a : ()) -> Result<crate::System::Runtime::CompilerServices::NativeCppClassAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}

// System.Runtime.CompilerServices.RequiredAttributeAttribute
// from System.Runtime.CompilerServices.VisualC
#[derive(Debug)]
pub struct RequiredAttributeAttribute {
    h : i64
}

impl ::sgrust_core::SGRustValue for RequiredAttributeAttribute {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_CompilerServices_RequiredAttributeAttribute_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_CompilerServices_RequiredAttributeAttribute_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for RequiredAttributeAttribute {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl RequiredAttributeAttribute {

    // .ctor(System.Type)
    pub fn ctor__1__Type(_requiredContract : &::System_Runtime::System::Type) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_CompilerServices_RequiredAttributeAttribute_ctor__1__Type(thrown : *mut i64, _requiredContract : i64) -> i64;
        }
        unsafe {
            let h = System_Runtime_CompilerServices_RequiredAttributeAttribute_ctor__1__Type(&mut __thrown, _requiredContract.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Type get_RequiredContract()
    pub fn Type__get_RequiredContract__0(&self) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_CompilerServices_RequiredAttributeAttribute_Type__get_RequiredContract__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_CompilerServices_RequiredAttributeAttribute_Type__get_RequiredContract__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Attribute> for RequiredAttributeAttribute {
    fn into(self) -> ::System_Runtime::System::Attribute {
        unsafe { ::System_Runtime::System::Attribute::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for RequiredAttributeAttribute {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_Type_get_RequiredContract_t_m<TA> {
    fn get_RequiredContract(&self, args : TA) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_get_RequiredContract_r_m<> {
    fn get_RequiredContract(&self, ) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_Type_get_RequiredContract_0_m<> {
    fn get_RequiredContract_0(&self, ) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredAttributeAttribute_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Runtime::CompilerServices::RequiredAttributeAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_ctor_r_f<TA1> {
    fn ctor(p1 : TA1) -> Result<crate::System::Runtime::CompilerServices::RequiredAttributeAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredAttributeAttribute_ctor_1_f<TA1> {
    fn ctor_1(p1 : TA1) -> Result<crate::System::Runtime::CompilerServices::RequiredAttributeAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredContract_s_m<> {
    fn RequiredContract(&self, ) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception>;
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_get_RequiredContract_r_m<> for RequiredAttributeAttribute {
    fn get_RequiredContract(&self, ) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception> {
        self.Type__get_RequiredContract__0()
    }
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_Type_get_RequiredContract_0_m<> for RequiredAttributeAttribute {
    fn get_RequiredContract_0(&self, ) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception> {
        self.Type__get_RequiredContract__0()
    }
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_Type_get_RequiredContract_t_m<()> for RequiredAttributeAttribute {
    fn get_RequiredContract(&self, _a : ()) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception> {
        self.Type__get_RequiredContract__0()
    }
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_ctor_r_f<&::System_Runtime::System::Type> for RequiredAttributeAttribute {
    fn ctor(p1 : &::System_Runtime::System::Type) -> Result<crate::System::Runtime::CompilerServices::RequiredAttributeAttribute,::System_Runtime::System::Exception> {
        Self::ctor__1__Type(p1)
    }
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredAttributeAttribute_ctor_1_f<&::System_Runtime::System::Type> for RequiredAttributeAttribute {
    fn ctor_1(p1 : &::System_Runtime::System::Type) -> Result<crate::System::Runtime::CompilerServices::RequiredAttributeAttribute,::System_Runtime::System::Exception> {
        Self::ctor__1__Type(p1)
    }
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredAttributeAttribute_ctor_t_f<(&::System_Runtime::System::Type,)> for RequiredAttributeAttribute {
    fn ctor(a : (&::System_Runtime::System::Type,)) -> Result<crate::System::Runtime::CompilerServices::RequiredAttributeAttribute,::System_Runtime::System::Exception> {
        Self::ctor__1__Type(a.0,)
    }
}
impl System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredContract_s_m<> for RequiredAttributeAttribute {
    fn RequiredContract(&self, ) -> Result<::System_Runtime::System::Type,::System_Runtime::System::Exception> {
        self.Type__get_RequiredContract__0()
    }
}

// System.Runtime.CompilerServices.ScopelessEnumAttribute
// from System.Runtime.CompilerServices.VisualC
#[derive(Debug)]
pub struct ScopelessEnumAttribute {
    h : i64
}

impl ::sgrust_core::SGRustValue for ScopelessEnumAttribute {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_CompilerServices_ScopelessEnumAttribute_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_CompilerServices_ScopelessEnumAttribute_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for ScopelessEnumAttribute {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ScopelessEnumAttribute {

    // .ctor()
    pub fn ctor__0() -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_CompilerServices_ScopelessEnumAttribute_ctor__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let h = System_Runtime_CompilerServices_ScopelessEnumAttribute_ctor__0(&mut __thrown);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Attribute> for ScopelessEnumAttribute {
    fn into(self) -> ::System_Runtime::System::Attribute {
        unsafe { ::System_Runtime::System::Attribute::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for ScopelessEnumAttribute {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ScopelessEnumAttribute_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Runtime::CompilerServices::ScopelessEnumAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ctor_r_f<> {
    fn ctor() -> Result<crate::System::Runtime::CompilerServices::ScopelessEnumAttribute,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ScopelessEnumAttribute_ctor_0_f<> {
    fn ctor_0() -> Result<crate::System::Runtime::CompilerServices::ScopelessEnumAttribute,::System_Runtime::System::Exception>;
}
impl System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ctor_r_f<> for ScopelessEnumAttribute {
    fn ctor() -> Result<crate::System::Runtime::CompilerServices::ScopelessEnumAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ScopelessEnumAttribute_ctor_0_f<> for ScopelessEnumAttribute {
    fn ctor_0() -> Result<crate::System::Runtime::CompilerServices::ScopelessEnumAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ScopelessEnumAttribute_ctor_t_f<()> for ScopelessEnumAttribute {
    fn ctor(_a : ()) -> Result<crate::System::Runtime::CompilerServices::ScopelessEnumAttribute,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}

} // System.Runtime.CompilerServices

} // System.Runtime

} // System

pub mod overloads_with_count {
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_CppInlineNamespaceAttribute_ctor_1_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_HasCopySemanticsAttribute_ctor_0_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_NativeCppClassAttribute_overload_NativeCppClassAttribute_ctor_0_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_Type_get_RequiredContract_0_m;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredAttributeAttribute_ctor_1_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ScopelessEnumAttribute_ctor_0_f;
}
pub mod overloads_with_tuple {
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_CppInlineNamespaceAttribute_ctor_t_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_HasCopySemanticsAttribute_ctor_t_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_NativeCppClassAttribute_overload_NativeCppClassAttribute_ctor_t_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_Type_get_RequiredContract_t_m;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredAttributeAttribute_ctor_t_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ScopelessEnumAttribute_ctor_t_f;
}
pub mod overloads_special {
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_RequiredContract_s_m;
}
pub mod overloads_risky {
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_CppInlineNamespaceAttribute_overload_ctor_r_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_HasCopySemanticsAttribute_overload_ctor_r_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_NativeCppClassAttribute_overload_ctor_r_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_get_RequiredContract_r_m;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_RequiredAttributeAttribute_overload_ctor_r_f;
pub use crate::System::Runtime::CompilerServices::System_Runtime_CompilerServices_ScopelessEnumAttribute_overload_ctor_r_f;
}

