// this file is automatically generated
// Copyright 2020 SourceGear
#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_unsafe)]
#![allow(unused_imports)]
#![allow(unused_parens)]

extern {
    fn __drop_handle(self_h : i64);
    fn __copy_handle(self_h : i64) -> i64;
}

// System
pub mod System {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Resources
pub mod Resources {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Resources.IResourceWriter
// from System.Resources.Writer
#[derive(Debug)]
pub struct IResourceWriter {
    h : i64
}

impl ::sgrust_core::SGRustValue for IResourceWriter {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Resources_IResourceWriter_get_type_handle() -> i64;
        }
        unsafe {
            return System_Resources_IResourceWriter_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for IResourceWriter {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl IResourceWriter {

    // System.Void AddResource(System.String, System.Byte[])
    pub fn void__AddResource__2__String_u8Array(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_IResourceWriter_void__AddResource__2__String_u8Array(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_IResourceWriter_void__AddResource__2__String_u8Array(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.Object)
    pub fn void__AddResource__2__String_Object(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::Object)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_IResourceWriter_void__AddResource__2__String_Object(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_IResourceWriter_void__AddResource__2__String_Object(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.String)
    pub fn void__AddResource__2__String_String(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_IResourceWriter_void__AddResource__2__String_String(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_IResourceWriter_void__AddResource__2__String_String(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void Close()
    pub fn void__Close__0(&self)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_IResourceWriter_void__Close__0(thrown : *mut i64, self_h : i64);
        }
        unsafe {
            System_Resources_IResourceWriter_void__Close__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void Generate()
    pub fn void__Generate__0(&self)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_IResourceWriter_void__Generate__0(thrown : *mut i64, self_h : i64);
        }
        unsafe {
            System_Resources_IResourceWriter_void__Generate__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

pub trait System_Resources_IResourceWriter_overload_void_AddResource_t_m<TA> {
    fn AddResource(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_AddResource_r_m<TA1,TA2> {
    fn AddResource(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_void_AddResource_2_m<TA1,TA2> {
    fn AddResource_2(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_void_Close_t_m<TA> {
    fn Close(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_Close_r_m<> {
    fn Close(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_void_Close_0_m<> {
    fn Close_0(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_void_Generate_t_m<TA> {
    fn Generate(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_Generate_r_m<> {
    fn Generate(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_IResourceWriter_overload_void_Generate_0_m<> {
    fn Generate_0(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
impl System_Resources_IResourceWriter_overload_AddResource_r_m<&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>> for IResourceWriter {
    fn AddResource(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_u8Array(p1,p2)
    }
}
impl System_Resources_IResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>> for IResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_u8Array(p1,p2)
    }
}
impl System_Resources_IResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>)> for IResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_u8Array(a.0,a.1)
    }
}
impl System_Resources_IResourceWriter_overload_AddResource_r_m<&::System_Runtime::System::String,&::System_Runtime::System::Object> for IResourceWriter {
    fn AddResource(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Object)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Object(p1,p2)
    }
}
impl System_Resources_IResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::Object> for IResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Object)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Object(p1,p2)
    }
}
impl System_Resources_IResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::Object)> for IResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::Object))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Object(a.0,a.1)
    }
}
impl System_Resources_IResourceWriter_overload_AddResource_r_m<&::System_Runtime::System::String,&::System_Runtime::System::String> for IResourceWriter {
    fn AddResource(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_String(p1,p2)
    }
}
impl System_Resources_IResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::String> for IResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_String(p1,p2)
    }
}
impl System_Resources_IResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::String)> for IResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::String))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_String(a.0,a.1)
    }
}
impl System_Resources_IResourceWriter_overload_Close_r_m<> for IResourceWriter {
    fn Close(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Close__0()
    }
}
impl System_Resources_IResourceWriter_overload_void_Close_0_m<> for IResourceWriter {
    fn Close_0(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Close__0()
    }
}
impl System_Resources_IResourceWriter_overload_void_Close_t_m<()> for IResourceWriter {
    fn Close(&self, _a : ())-> Result<(),::System_Runtime::System::Exception> {
        self.void__Close__0()
    }
}
impl System_Resources_IResourceWriter_overload_Generate_r_m<> for IResourceWriter {
    fn Generate(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Generate__0()
    }
}
impl System_Resources_IResourceWriter_overload_void_Generate_0_m<> for IResourceWriter {
    fn Generate_0(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Generate__0()
    }
}
impl System_Resources_IResourceWriter_overload_void_Generate_t_m<()> for IResourceWriter {
    fn Generate(&self, _a : ())-> Result<(),::System_Runtime::System::Exception> {
        self.void__Generate__0()
    }
}

// System.Resources.ResourceWriter
// from System.Resources.Writer
#[derive(Debug)]
pub struct ResourceWriter {
    h : i64
}

impl ::sgrust_core::SGRustValue for ResourceWriter {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Resources_ResourceWriter_get_type_handle() -> i64;
        }
        unsafe {
            return System_Resources_ResourceWriter_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for ResourceWriter {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ResourceWriter {

    // .ctor(System.IO.Stream)
    pub fn ctor__1__Stream(_stream : &::System_Runtime::System::IO::Stream) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_ctor__1__Stream(thrown : *mut i64, _stream : i64) -> i64;
        }
        unsafe {
            let h = System_Resources_ResourceWriter_ctor__1__Stream(&mut __thrown, _stream.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String)
    pub fn ctor__1__String(_fileName : &::System_Runtime::System::String) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_ctor__1__String(thrown : *mut i64, _fileName : i64) -> i64;
        }
        unsafe {
            let h = System_Resources_ResourceWriter_ctor__1__String(&mut __thrown, _fileName.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Func<System.Type,System.String> get_TypeNameConverter()
    pub fn System_Func_System_Type_string___get_TypeNameConverter__0(&self) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_System_Func_System_Type_string___get_TypeNameConverter__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Resources_ResourceWriter_System_Func_System_Type_string___get_TypeNameConverter__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Void set_TypeNameConverter(System.Func<System.Type,System.String>)
    pub fn void__set_TypeNameConverter__1__System_Func_System_Type_string_(&self, _value : &::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__set_TypeNameConverter__1__System_Func_System_Type_string_(thrown : *mut i64, self_h : i64, _value : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__set_TypeNameConverter__1__System_Func_System_Type_string_(&mut __thrown, self.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.Byte[])
    pub fn void__AddResource__2__String_u8Array(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__AddResource__2__String_u8Array(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__AddResource__2__String_u8Array(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.IO.Stream)
    pub fn void__AddResource__2__String_Stream(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::IO::Stream)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__AddResource__2__String_Stream(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__AddResource__2__String_Stream(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.IO.Stream, System.Boolean)
    pub fn void__AddResource__3__String_Stream_bool(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::IO::Stream, _closeAfterWrite : bool)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__AddResource__3__String_Stream_bool(thrown : *mut i64, self_h : i64, _name : i64, _value : i64, _closeAfterWrite : i32);
        }
        unsafe {
            System_Resources_ResourceWriter_void__AddResource__3__String_Stream_bool(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle(), if _closeAfterWrite {1} else {0});
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.Object)
    pub fn void__AddResource__2__String_Object(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::Object)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__AddResource__2__String_Object(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__AddResource__2__String_Object(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResource(System.String, System.String)
    pub fn void__AddResource__2__String_String(&self, _name : &::System_Runtime::System::String, _value : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__AddResource__2__String_String(thrown : *mut i64, self_h : i64, _name : i64, _value : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__AddResource__2__String_String(&mut __thrown, self.get_handle(), _name.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void AddResourceData(System.String, System.String, System.Byte[])
    pub fn void__AddResourceData__3__String_String_u8Array(&self, _name : &::System_Runtime::System::String, _typeName : &::System_Runtime::System::String, _serializedData : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__AddResourceData__3__String_String_u8Array(thrown : *mut i64, self_h : i64, _name : i64, _typeName : i64, _serializedData : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__AddResourceData__3__String_String_u8Array(&mut __thrown, self.get_handle(), _name.get_handle(), _typeName.get_handle(), _serializedData.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void Close()
    pub fn void__Close__0(&self)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__Close__0(thrown : *mut i64, self_h : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__Close__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void Dispose()
    pub fn void__Dispose__0(&self)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__Dispose__0(thrown : *mut i64, self_h : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__Dispose__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void Generate()
    pub fn void__Generate__0(&self)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Resources_ResourceWriter_void__Generate__0(thrown : *mut i64, self_h : i64);
        }
        unsafe {
            System_Resources_ResourceWriter_void__Generate__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Object> for ResourceWriter {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::IDisposable> for ResourceWriter {
    fn into(self) -> ::System_Runtime::System::IDisposable {
        extern {
            fn System_Resources_ResourceWriter_to_IDisposable(self_h : i64) -> i64;
        }
        unsafe {
            let h = System_Resources_ResourceWriter_to_IDisposable(self.get_handle());
            return SGRustObjectHandle::from_handle(h);
        }
    }
}

impl Into<crate::System::Resources::IResourceWriter> for ResourceWriter {
    fn into(self) -> crate::System::Resources::IResourceWriter {
        extern {
            fn System_Resources_ResourceWriter_to_IResourceWriter(self_h : i64) -> i64;
        }
        unsafe {
            let h = System_Resources_ResourceWriter_to_IResourceWriter(self.get_handle());
            return SGRustObjectHandle::from_handle(h);
        }
    }
}

pub trait System_Resources_ResourceWriter_overload_System_Func_System_Type_string__get_TypeNameConverter_t_m<TA> {
    fn get_TypeNameConverter(&self, args : TA) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_get_TypeNameConverter_r_m<> {
    fn get_TypeNameConverter(&self, ) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_System_Func_System_Type_string__get_TypeNameConverter_0_m<> {
    fn get_TypeNameConverter_0(&self, ) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_set_TypeNameConverter_t_m<TA> {
    fn set_TypeNameConverter(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_set_TypeNameConverter_r_m<TA1> {
    fn set_TypeNameConverter(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_set_TypeNameConverter_1_m<TA1> {
    fn set_TypeNameConverter_1(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_AddResource_t_m<TA> {
    fn AddResource(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_AddResource_2_m<TA1,TA2> {
    fn AddResource_2(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_AddResource_3_m<TA1,TA2,TA3> {
    fn AddResource_3(&self, p1 : TA1,p2 : TA2,p3 : TA3)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_AddResourceData_t_m<TA> {
    fn AddResourceData(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_AddResourceData_r_m<TA1,TA2,TA3> {
    fn AddResourceData(&self, p1 : TA1,p2 : TA2,p3 : TA3)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_AddResourceData_3_m<TA1,TA2,TA3> {
    fn AddResourceData_3(&self, p1 : TA1,p2 : TA2,p3 : TA3)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_Close_t_m<TA> {
    fn Close(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_Close_r_m<> {
    fn Close(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_Close_0_m<> {
    fn Close_0(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_Dispose_t_m<TA> {
    fn Dispose(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_Dispose_r_m<> {
    fn Dispose(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_Dispose_0_m<> {
    fn Dispose_0(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_Generate_t_m<TA> {
    fn Generate(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_Generate_r_m<> {
    fn Generate(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_void_Generate_0_m<> {
    fn Generate_0(&self, )-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_ResourceWriter_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_ctor_r_f<TA1> {
    fn ctor(p1 : TA1) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_ResourceWriter_ctor_1_f<TA1> {
    fn ctor_1(p1 : TA1) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception>;
}
pub trait System_Resources_ResourceWriter_overload_TypeNameConverter_s_m<> {
    fn TypeNameConverter(&self, ) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
impl System_Resources_ResourceWriter_overload_get_TypeNameConverter_r_m<> for ResourceWriter {
    fn get_TypeNameConverter(&self, ) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.System_Func_System_Type_string___get_TypeNameConverter__0()
    }
}
impl System_Resources_ResourceWriter_overload_System_Func_System_Type_string__get_TypeNameConverter_0_m<> for ResourceWriter {
    fn get_TypeNameConverter_0(&self, ) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.System_Func_System_Type_string___get_TypeNameConverter__0()
    }
}
impl System_Resources_ResourceWriter_overload_System_Func_System_Type_string__get_TypeNameConverter_t_m<()> for ResourceWriter {
    fn get_TypeNameConverter(&self, _a : ()) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.System_Func_System_Type_string___get_TypeNameConverter__0()
    }
}
impl System_Resources_ResourceWriter_overload_set_TypeNameConverter_r_m<&::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>> for ResourceWriter {
    fn set_TypeNameConverter(&self, p1 : &::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_TypeNameConverter__1__System_Func_System_Type_string_(p1)
    }
}
impl System_Resources_ResourceWriter_overload_void_set_TypeNameConverter_1_m<&::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>> for ResourceWriter {
    fn set_TypeNameConverter_1(&self, p1 : &::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_TypeNameConverter__1__System_Func_System_Type_string_(p1)
    }
}
impl System_Resources_ResourceWriter_overload_void_set_TypeNameConverter_t_m<(&::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,)> for ResourceWriter {
    fn set_TypeNameConverter(&self, a : (&::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,))-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_TypeNameConverter__1__System_Func_System_Type_string_(a.0,)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>> for ResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_u8Array(p1,p2)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>)> for ResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_u8Array(a.0,a.1)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::IO::Stream> for ResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::IO::Stream)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Stream(p1,p2)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::IO::Stream)> for ResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::IO::Stream))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Stream(a.0,a.1)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::Object> for ResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Object)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Object(p1,p2)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::Object)> for ResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::Object))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_Object(a.0,a.1)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_2_m<&::System_Runtime::System::String,&::System_Runtime::System::String> for ResourceWriter {
    fn AddResource_2(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_String(p1,p2)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::String)> for ResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::String))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__2__String_String(a.0,a.1)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_3_m<&::System_Runtime::System::String,&::System_Runtime::System::IO::Stream,bool> for ResourceWriter {
    fn AddResource_3(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::IO::Stream,p3 : bool)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__3__String_Stream_bool(p1,p2,p3)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResource_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::IO::Stream,bool)> for ResourceWriter {
    fn AddResource(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::IO::Stream,bool))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResource__3__String_Stream_bool(a.0,a.1,a.2)
    }
}
impl System_Resources_ResourceWriter_overload_AddResourceData_r_m<&::System_Runtime::System::String,&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>> for ResourceWriter {
    fn AddResourceData(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::String,p3 : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResourceData__3__String_String_u8Array(p1,p2,p3)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResourceData_3_m<&::System_Runtime::System::String,&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>> for ResourceWriter {
    fn AddResourceData_3(&self, p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::String,p3 : &::System_Runtime::System::Arr<u8>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResourceData__3__String_String_u8Array(p1,p2,p3)
    }
}
impl System_Resources_ResourceWriter_overload_void_AddResourceData_t_m<(&::System_Runtime::System::String,&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>)> for ResourceWriter {
    fn AddResourceData(&self, a : (&::System_Runtime::System::String,&::System_Runtime::System::String,&::System_Runtime::System::Arr<u8>))-> Result<(),::System_Runtime::System::Exception> {
        self.void__AddResourceData__3__String_String_u8Array(a.0,a.1,a.2)
    }
}
impl System_Resources_ResourceWriter_overload_Close_r_m<> for ResourceWriter {
    fn Close(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Close__0()
    }
}
impl System_Resources_ResourceWriter_overload_void_Close_0_m<> for ResourceWriter {
    fn Close_0(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Close__0()
    }
}
impl System_Resources_ResourceWriter_overload_void_Close_t_m<()> for ResourceWriter {
    fn Close(&self, _a : ())-> Result<(),::System_Runtime::System::Exception> {
        self.void__Close__0()
    }
}
impl System_Resources_ResourceWriter_overload_Dispose_r_m<> for ResourceWriter {
    fn Dispose(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Dispose__0()
    }
}
impl System_Resources_ResourceWriter_overload_void_Dispose_0_m<> for ResourceWriter {
    fn Dispose_0(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Dispose__0()
    }
}
impl System_Resources_ResourceWriter_overload_void_Dispose_t_m<()> for ResourceWriter {
    fn Dispose(&self, _a : ())-> Result<(),::System_Runtime::System::Exception> {
        self.void__Dispose__0()
    }
}
impl System_Resources_ResourceWriter_overload_Generate_r_m<> for ResourceWriter {
    fn Generate(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Generate__0()
    }
}
impl System_Resources_ResourceWriter_overload_void_Generate_0_m<> for ResourceWriter {
    fn Generate_0(&self, )-> Result<(),::System_Runtime::System::Exception> {
        self.void__Generate__0()
    }
}
impl System_Resources_ResourceWriter_overload_void_Generate_t_m<()> for ResourceWriter {
    fn Generate(&self, _a : ())-> Result<(),::System_Runtime::System::Exception> {
        self.void__Generate__0()
    }
}
impl System_Resources_ResourceWriter_overload_ctor_r_f<&::System_Runtime::System::IO::Stream> for ResourceWriter {
    fn ctor(p1 : &::System_Runtime::System::IO::Stream) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception> {
        Self::ctor__1__Stream(p1)
    }
}
impl System_Resources_ResourceWriter_overload_ResourceWriter_ctor_1_f<&::System_Runtime::System::IO::Stream> for ResourceWriter {
    fn ctor_1(p1 : &::System_Runtime::System::IO::Stream) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception> {
        Self::ctor__1__Stream(p1)
    }
}
impl System_Resources_ResourceWriter_overload_ResourceWriter_ctor_t_f<(&::System_Runtime::System::IO::Stream,)> for ResourceWriter {
    fn ctor(a : (&::System_Runtime::System::IO::Stream,)) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception> {
        Self::ctor__1__Stream(a.0,)
    }
}
impl System_Resources_ResourceWriter_overload_ctor_r_f<&::System_Runtime::System::String> for ResourceWriter {
    fn ctor(p1 : &::System_Runtime::System::String) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_Resources_ResourceWriter_overload_ResourceWriter_ctor_1_f<&::System_Runtime::System::String> for ResourceWriter {
    fn ctor_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_Resources_ResourceWriter_overload_ResourceWriter_ctor_t_f<(&::System_Runtime::System::String,)> for ResourceWriter {
    fn ctor(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Resources::ResourceWriter,::System_Runtime::System::Exception> {
        Self::ctor__1__String(a.0,)
    }
}
impl System_Resources_ResourceWriter_overload_TypeNameConverter_s_m<> for ResourceWriter {
    fn TypeNameConverter(&self, ) -> Result<::System_Runtime::System::Func_2<::System_Runtime::System::Type,::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.System_Func_System_Type_string___get_TypeNameConverter__0()
    }
}

} // System.Resources

} // System

pub mod overloads_with_count {
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_void_AddResource_2_m;
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_void_Close_0_m;
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_void_Generate_0_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_System_Func_System_Type_string__get_TypeNameConverter_0_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_set_TypeNameConverter_1_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_AddResource_2_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_AddResource_3_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_AddResourceData_3_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_Close_0_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_Dispose_0_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_Generate_0_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_ResourceWriter_ctor_1_f;
}
pub mod overloads_with_tuple {
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_void_AddResource_t_m;
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_void_Close_t_m;
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_void_Generate_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_System_Func_System_Type_string__get_TypeNameConverter_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_set_TypeNameConverter_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_AddResource_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_AddResourceData_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_Close_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_Dispose_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_void_Generate_t_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_ResourceWriter_ctor_t_f;
}
pub mod overloads_special {
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_TypeNameConverter_s_m;
}
pub mod overloads_risky {
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_AddResource_r_m;
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_Close_r_m;
pub use crate::System::Resources::System_Resources_IResourceWriter_overload_Generate_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_get_TypeNameConverter_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_set_TypeNameConverter_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_AddResourceData_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_Close_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_Dispose_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_Generate_r_m;
pub use crate::System::Resources::System_Resources_ResourceWriter_overload_ctor_r_f;
}

