// @generated by Rustlyn.Bindings. Do not edit by hand.
#nullable enable
using System.Management.Automation;
using Rustlyn.PowerShellSupport;

namespace Rustlyn.PowerShellCmdlets;

[Cmdlet(VerbsData.ConvertTo, "RustJson")]
[OutputType(typeof(string))]
public sealed class ConvertToRustJsonCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public int Depth { get; set; } = 2;

    [Parameter]
    public SwitchParameter Compress { get; set; }

    [Parameter]
    public SwitchParameter EnumsAsStrings { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_json_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_json_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_json_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustJson")]
[OutputType(typeof(System.Management.Automation.PSObject), typeof(System.Collections.Generic.IDictionary<string, object>))]
public sealed class ConvertFromRustJsonCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public SwitchParameter AsHashtable { get; set; }

    [Parameter]
    public SwitchParameter NoEnumerate { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_json_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_json_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_json_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertTo, "RustCsv")]
[OutputType(typeof(string))]
public sealed class ConvertToRustCsvCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public char Delimiter { get; set; }

    [Parameter]
    public SwitchParameter UseCulture { get; set; }

    [Parameter]
    public SwitchParameter NoTypeInformation { get; set; }

    [Parameter]
    public SwitchParameter IncludeTypeInformation { get; set; }

    [Parameter]
    public SwitchParameter NoHeader { get; set; }

    [Parameter]
    public string[]? QuoteFields { get; set; }

    [Parameter]
    [ValidateSet("Always", "AsNeeded", "Never")]
    public string? UseQuotes { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_csv_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_csv_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_csv_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustCsv")]
[OutputType(typeof(System.Management.Automation.PSObject))]
public sealed class ConvertFromRustCsvCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    [AllowEmptyString]
    public string[]? InputObject { get; set; }

    [Parameter]
    public char Delimiter { get; set; }

    [Parameter]
    public SwitchParameter UseCulture { get; set; }

    [Parameter]
    public string[]? Header { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_csv_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_csv_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_csv_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertTo, "RustToml")]
[OutputType(typeof(string))]
public sealed class ConvertToRustTomlCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public int Depth { get; set; } = 8;

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_toml_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_toml_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_toml_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustToml")]
[OutputType(typeof(System.Management.Automation.PSObject), typeof(System.Collections.Generic.IDictionary<string, object>))]
public sealed class ConvertFromRustTomlCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    public object? InputObject { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_toml_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_toml_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_toml_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertTo, "RustXml")]
[OutputType(typeof(string), typeof(System.Xml.XmlDocument), typeof(System.IO.Stream))]
public sealed class ConvertToRustXmlCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public int Depth { get; set; } = 2;

    [Parameter]
    public SwitchParameter NoTypeInformation { get; set; }

    [Parameter]
    [ValidateSet("String", "Document", "Stream")]
    public string As { get; set; } = "Document";

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_xml_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_xml_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var captureXmlStream = string.Equals(As, "Stream", StringComparison.OrdinalIgnoreCase) && methodName.EndsWith("_end_processing", StringComparison.Ordinal);
        var capturedOutput = captureXmlStream ? new System.Collections.Generic.List<object?>() : null;
        var boundParameters = captureXmlStream
            ? new System.Collections.Generic.Dictionary<string, object?>(MyInvocation.BoundParameters, StringComparer.OrdinalIgnoreCase) { ["As"] = "String" }
            : MyInvocation.BoundParameters;
        var context = new PowerShellCmdletContext(
            value =>
            {
                if (capturedOutput is null)
                {
                    WriteObject(value);
                }
                else
                {
                    capturedOutput.Add(value);
                }
            },
            (value, enumerateCollection) =>
            {
                if (capturedOutput is null)
                {
                    WriteObject(value, enumerateCollection);
                }
                else
                {
                    capturedOutput.Add(value);
                }
            },
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            boundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
        if (capturedOutput is not null)
        {
            foreach (var output in capturedOutput)
            {
                var xml = output?.ToString() ?? string.Empty;
                WriteObject(new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(xml)), enumerateCollection: false);
            }
        }
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_xml_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustXml")]
[OutputType(typeof(System.Xml.XmlDocument))]
public sealed class ConvertFromRustXmlCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    public object? InputObject { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_xml_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_xml_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_xml_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertTo, "RustYaml")]
[OutputType(typeof(string))]
public sealed class ConvertToRustYamlCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_yaml_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_yaml_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_yaml_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustYaml")]
[OutputType(typeof(System.Management.Automation.PSObject), typeof(System.Collections.Generic.IDictionary<string, object>))]
public sealed class ConvertFromRustYamlCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public SwitchParameter AsHashtable { get; set; }

    [Parameter]
    public SwitchParameter NoEnumerate { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_yaml_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_yaml_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_yaml_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertTo, "RustBson")]
[OutputType(typeof(byte[]))]
public sealed class ConvertToRustBsonCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public int Depth { get; set; } = 8;

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_bson_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_bson_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_bson_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustBson")]
[OutputType(typeof(System.Management.Automation.PSObject), typeof(System.Collections.Generic.IDictionary<string, object>))]
public sealed class ConvertFromRustBsonCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public SwitchParameter AsHashtable { get; set; }

    [Parameter]
    public SwitchParameter NoEnumerate { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_bson_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_bson_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_bson_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertTo, "RustCbor")]
[OutputType(typeof(byte[]))]
public sealed class ConvertToRustCborCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public int Depth { get; set; } = 8;

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_cbor_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_cbor_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_to_rust_cbor_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}

[Cmdlet(VerbsData.ConvertFrom, "RustCbor")]
[OutputType(typeof(System.Management.Automation.PSObject), typeof(System.Collections.Generic.IDictionary<string, object>))]
public sealed class ConvertFromRustCborCommand : PSCmdlet
{
    private readonly PowerShellCmdletCancellation _cancellation = new();
    private int _lifecycleStateHandle;

    [Parameter(Position = 0, ValueFromPipeline = true, Mandatory = true)]
    public object? InputObject { get; set; }

    [Parameter]
    public SwitchParameter AsHashtable { get; set; }

    [Parameter]
    public SwitchParameter NoEnumerate { get; set; }

    protected override void ProcessRecord()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_cbor_process_record", InputObject);
        }
        catch
        {
            ReleaseLifecycleState();
            throw;
        }
    }

    protected override void EndProcessing()
    {
        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_cbor_end_processing", null);
        }
        finally
        {
            ReleaseLifecycleState();
        }
    }

    protected override void StopProcessing()
        => _cancellation.RequestCancellation();

    private void InvokeRustEntrypoint(string engineAssemblyName, string typeName, string methodName, object? inputObject, bool checkCancellation = true)
    {
        var context = new PowerShellCmdletContext(
            value => WriteObject(value),
            (value, enumerateCollection) => WriteObject(value, enumerateCollection),
            WriteVerbose,
            WriteWarning,
            message => WriteError(CreateErrorRecord(message)),
            WriteError,
            ThrowTerminatingError,
            target => ShouldProcess(target),
            (target, action) => ShouldProcess(target, action),
            MyInvocation.BoundParameters,
            inputObject,
            _cancellation,
            EnsureLifecycleStateHandle());
        PowerShellGeneratedCmdletInvoker.InvokeLifecycle(engineAssemblyName, typeName, methodName, context, checkCancellation);
        PowerShellCmdletBridge.FlushPendingOutputs(context);
    }

    private int EnsureLifecycleStateHandle()
    {
        if (_lifecycleStateHandle == 0)
        {
            _lifecycleStateHandle = PowerShellGeneratedCmdletInvoker.CreateLifecycleStateHandle();
        }

        return _lifecycleStateHandle;
    }

    private void ReleaseLifecycleState()
    {
        var lifecycleStateHandle = _lifecycleStateHandle;
        if (lifecycleStateHandle == 0)
        {
            return;
        }

        try
        {
            InvokeRustEntrypoint("rustlyn_powershell_format_cmdlets.dll", "Rustlyn.GeneratedModule", "convert_from_rust_cbor_cleanup", null, checkCancellation: false);
        }
        finally
        {
            _lifecycleStateHandle = 0;
            PowerShellGeneratedCmdletInvoker.ReleaseLifecycleStateHandle(lifecycleStateHandle);
        }
    }

    private static ErrorRecord CreateErrorRecord(string message)
        => new(new RuntimeException(message), "RustlynPowerShellCmdletError", ErrorCategory.NotSpecified, null);
}
