// @generated by Rustlyn.Bindings. Do not edit by hand.

unsafe extern "C" {
    fn rustlyn_bindgen_system_console_write_line_utf8(value_ptr: *const u8, value_length: i64) -> i32;
    fn rustlyn_bindgen_system_console_write_line_string(string_handle: i32) -> i32;
    fn rustlyn_bindgen_system_environment_get_command_line_args(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_environment_current_directory(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_directory_get_current_directory(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_directory_get_files_string_string(
        path_handle: i32,
        search_pattern_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_io_file_read_all_lines_utf8(
        path_ptr: *const u8,
        path_length: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_io_file_read_all_lines_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_change_extension_string_string(
        path_handle: i32,
        extension_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_io_path_combine_string_string(
        path1_handle: i32,
        path2_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_io_path_ends_in_directory_separator_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_get_directory_name_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_get_extension_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_get_file_name_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_get_file_name_without_extension_string(
        path_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_io_path_get_full_path_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_get_path_root_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_get_relative_path_string_string(
        relative_to_handle: i32,
        path_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_io_path_get_temp_path(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_has_extension_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_is_path_fully_qualified_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_io_path_is_path_rooted_string(path_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_math_abs_f64(value: f64, exception_out: *mut i32) -> f64;
    fn rustlyn_bindgen_system_math_sqrt_f64(value: f64, exception_out: *mut i32) -> f64;
    fn rustlyn_bindgen_system_mathf_abs_f32(value: f32, exception_out: *mut i32) -> f32;
    fn rustlyn_bindgen_system_mathf_cos_f32(value: f32, exception_out: *mut i32) -> f32;
    fn rustlyn_bindgen_system_mathf_max_f32_f32(x: f32, y: f32, exception_out: *mut i32) -> f32;
    fn rustlyn_bindgen_system_mathf_min_f32_f32(x: f32, y: f32, exception_out: *mut i32) -> f32;
    fn rustlyn_bindgen_system_mathf_sin_f32(value: f32, exception_out: *mut i32) -> f32;
    fn rustlyn_bindgen_system_mathf_sqrt_f32(value: f32, exception_out: *mut i32) -> f32;
    fn rustlyn_bindgen_system_string_from_utf8(value_ptr: *const u8, value_length: i64, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_string_len(string_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_string_utf8_len(string_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_string_copy_utf8(
        string_handle: i32,
        destination_ptr: *mut u8,
        destination_capacity: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_contains_utf8(
        string_handle: i32,
        needle_ptr: *const u8,
        needle_length: i64,
        comparison: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_contains_string(
        string_handle: i32,
        needle_handle: i32,
        comparison: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_index_of_string(
        string_handle: i32,
        value_handle: i32,
        comparison: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_starts_with_string(
        string_handle: i32,
        value_handle: i32,
        comparison: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_ends_with_string(
        string_handle: i32,
        value_handle: i32,
        comparison: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_split_string_options(
        string_handle: i32,
        separator_handle: i32,
        options: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_substring_i32_i32(
        string_handle: i32,
        start_index: i32,
        length: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_replace_string_string(
        string_handle: i32,
        old_value_handle: i32,
        new_value_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_string_array_len(array_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_string_array_get(array_handle: i32, index: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_string_array_from_strings(
        first_handle: i32,
        second_handle: i32,
        third_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_int_array_from_i32_triplet(
        first: i32,
        second: i32,
        third: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_int_array_len(array_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_int_array_get(array_handle: i32, index: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_int_array_copy(
        array_handle: i32,
        destination_ptr: *mut i32,
        destination_capacity: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_byte_array_from_u8_triplet(
        first: i32,
        second: i32,
        third: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_byte_array_len(array_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_byte_array_get(array_handle: i32, index: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_byte_array_copy(
        array_handle: i32,
        destination_ptr: *mut u8,
        destination_capacity: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_time_span_from_milliseconds_f64(value: f64, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_time_span_ticks(time_span_handle: i32, exception_out: *mut i32) -> i64;
    fn rustlyn_bindgen_system_time_span_total_milliseconds(time_span_handle: i32, exception_out: *mut i32) -> f64;
    fn rustlyn_bindgen_system_time_span_to_string(time_span_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_date_time_offset_from_unix_time_milliseconds_i64(
        milliseconds: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_date_time_offset_to_unix_time_milliseconds(
        date_time_offset_handle: i32,
        exception_out: *mut i32,
    ) -> i64;
    fn rustlyn_bindgen_system_date_time_offset_to_string(date_time_offset_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_guid_parse_string(value_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_guid_to_string(guid_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_callback_apply_i32(
        i32_callback_ptr: fn(i32) -> i32,
        value: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_callback_apply_i32_i32(
        i32_i32_callback_ptr: fn(i32, i32) -> i32,
        left: i32,
        right: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_callback_transform_managed_string(
        string_transform_callback_ptr: fn(i32) -> i32,
        string_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_object_release(object_handle: i32) -> i32;
    fn rustlyn_bindgen_system_exception_release(exception_handle: i32) -> i32;
    fn rustlyn_bindgen_system_exception_get_type_name_utf8_len(exception_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_exception_get_type_name_utf8(
        exception_handle: i32,
        destination_ptr: *mut u8,
        destination_capacity: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_system_exception_get_message_utf8_len(exception_handle: i32, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_system_exception_get_message_utf8(
        exception_handle: i32,
        destination_ptr: *mut u8,
        destination_capacity: i64,
        exception_out: *mut i32,
    ) -> i32;
}

#[repr(i32)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StringComparison {
    CurrentCulture = 0,
    CurrentCultureIgnoreCase = 1,
    InvariantCulture = 2,
    InvariantCultureIgnoreCase = 3,
    Ordinal = 4,
    OrdinalIgnoreCase = 5,
}

impl StringComparison {
    pub fn as_i32(self) -> i32 {
        self as i32
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StringSplitOptions {
    bits: i32,
}

#[allow(non_upper_case_globals)]
impl StringSplitOptions {
    pub const None: Self = Self { bits: 0 };
    pub const RemoveEmptyEntries: Self = Self { bits: 1 };
    pub const TrimEntries: Self = Self { bits: 2 };

    pub fn union(self, other: Self) -> Self {
        Self { bits: self.bits | other.bits }
    }

    pub fn as_i32(self) -> i32 {
        self.bits
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Exception {
    handle: i32,
}

impl Exception {
    fn from_handle(handle: i32) -> Result<(), Self> {
        if handle == 0 {
            Ok(())
        } else {
            Err(Self { handle })
        }
    }

    pub fn release(self) -> Result<(), Self> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_exception_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }

    pub fn type_name_utf8_len(&self) -> Result<i32, Self> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_exception_get_type_name_utf8_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn copy_type_name_utf8_into(&self, buffer: &mut [u8]) -> Result<i32, Self> {
        let mut exception_handle = 0;
        let written = unsafe {
            rustlyn_bindgen_system_exception_get_type_name_utf8(
                self.handle,
                buffer.as_mut_ptr(),
                buffer.len() as i64,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(written)
    }

    pub fn message_utf8_len(&self) -> Result<i32, Self> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_exception_get_message_utf8_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn copy_message_utf8_into(&self, buffer: &mut [u8]) -> Result<i32, Self> {
        let mut exception_handle = 0;
        let written = unsafe {
            rustlyn_bindgen_system_exception_get_message_utf8(
                self.handle,
                buffer.as_mut_ptr(),
                buffer.len() as i64,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(written)
    }
}

pub mod callback {
    use crate::system::{Exception, ManagedString};

    pub fn apply_i32(callback: fn(i32) -> i32, value: i32) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let result = unsafe {
            super::rustlyn_bindgen_system_callback_apply_i32(
                callback,
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(result)
    }

    pub fn apply_i32_i32(callback: fn(i32, i32) -> i32, left: i32, right: i32) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let result = unsafe {
            super::rustlyn_bindgen_system_callback_apply_i32_i32(
                callback,
                left,
                right,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(result)
    }

    pub fn transform_managed_string(callback: fn(i32) -> i32, value: &ManagedString) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rustlyn_bindgen_system_callback_transform_managed_string(
                callback,
                value.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }
}

pub mod console {
    use crate::system::{Exception, ManagedString};

    pub fn write_line_utf8_parts(value_ptr: *const u8, value_len: i64) -> Result<(), Exception> {
        let exception_handle = unsafe {
            super::rustlyn_bindgen_system_console_write_line_utf8(
                value_ptr,
                value_len,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }

    pub fn write_line(value: &ManagedString) -> Result<(), Exception> {
        let exception_handle = unsafe {
            super::rustlyn_bindgen_system_console_write_line_string(
                value.handle(),
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub mod convert {
    use crate::system::{Exception, ManagedString};


}

pub mod environment {
    use crate::system::{Exception, ManagedString, ManagedStringArray};

    pub fn current_directory() -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rustlyn_bindgen_system_environment_current_directory(
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn get_command_line_args() -> Result<ManagedStringArray, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rustlyn_bindgen_system_environment_get_command_line_args(
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedStringArray::from_handle(object_handle))
    }
}

pub mod math {
    use crate::system::Exception;

    pub fn abs(value: f64) -> Result<f64, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_math_abs_f64(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn sqrt(value: f64) -> Result<f64, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_math_sqrt_f64(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }
}

pub mod mathf {
    use crate::system::Exception;

    pub fn abs(value: f32) -> Result<f32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_mathf_abs_f32(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn cos(value: f32) -> Result<f32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_mathf_cos_f32(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn max(x: f32, y: f32) -> Result<f32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_mathf_max_f32_f32(
                x,
                y,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn min(x: f32, y: f32) -> Result<f32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_mathf_min_f32_f32(
                x,
                y,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn sin(value: f32) -> Result<f32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_mathf_sin_f32(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn sqrt(value: f32) -> Result<f32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            super::rustlyn_bindgen_system_mathf_sqrt_f32(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }
}

pub mod time_span {
    use crate::system::{Exception, ManagedTimeSpan};

    pub fn from_milliseconds(value: f64) -> Result<ManagedTimeSpan, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rustlyn_bindgen_system_time_span_from_milliseconds_f64(
                value,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedTimeSpan::from_handle(object_handle))
    }
}

pub mod date_time_offset {
    use crate::system::{Exception, ManagedDateTimeOffset};

    pub fn from_unix_time_milliseconds(milliseconds: i64) -> Result<ManagedDateTimeOffset, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rustlyn_bindgen_system_date_time_offset_from_unix_time_milliseconds_i64(
                milliseconds,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedDateTimeOffset::from_handle(object_handle))
    }
}

pub mod guid {
    use crate::system::{Exception, ManagedGuid, ManagedString};

    pub fn parse(value: &ManagedString) -> Result<ManagedGuid, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rustlyn_bindgen_system_guid_parse_string(
                value.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedGuid::from_handle(object_handle))
    }
}

pub mod gc {
    use crate::system::Exception;


}

pub mod operating_system {
    use crate::system::Exception;


}

pub mod uri {
    use crate::system::{Exception, ManagedString};


}

pub mod io {
    pub mod directory {
        use crate::system::{Exception, ManagedString, ManagedStringArray};

        pub fn get_current_directory() -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_directory_get_current_directory(
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_files(path: &ManagedString, search_pattern: &ManagedString) -> Result<ManagedStringArray, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_directory_get_files_string_string(
                    path.handle(),
                    search_pattern.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedStringArray::from_handle(object_handle))
        }
    }

    pub mod file {
        use crate::system::{Exception, ManagedString, ManagedStringArray};

        pub fn read_all_lines_utf8_parts(path_ptr: *const u8, path_len: i64) -> Result<ManagedStringArray, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_file_read_all_lines_utf8(
                    path_ptr,
                    path_len,
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedStringArray::from_handle(object_handle))
        }

        pub fn read_all_lines(path: &ManagedString) -> Result<ManagedStringArray, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_file_read_all_lines_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedStringArray::from_handle(object_handle))
        }
    }

    pub mod path {
        use crate::system::{Exception, ManagedString};

        pub fn change_extension(path: &ManagedString, extension: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_change_extension_string_string(
                    path.handle(),
                    extension.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn combine(path1: &ManagedString, path2: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_combine_string_string(
                    path1.handle(),
                    path2.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn ends_in_directory_separator(path: &ManagedString) -> Result<i32, Exception> {
            let mut exception_handle = 0;
            let value = unsafe {
                super::super::rustlyn_bindgen_system_io_path_ends_in_directory_separator_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(value)
        }

        pub fn get_directory_name(path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_directory_name_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_extension(path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_extension_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_file_name(path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_file_name_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_file_name_without_extension(path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_file_name_without_extension_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_full_path(path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_full_path_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_path_root(path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_path_root_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_relative_path(relative_to: &ManagedString, path: &ManagedString) -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_relative_path_string_string(
                    relative_to.handle(),
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn get_temp_path() -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rustlyn_bindgen_system_io_path_get_temp_path(
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }

        pub fn has_extension(path: &ManagedString) -> Result<i32, Exception> {
            let mut exception_handle = 0;
            let value = unsafe {
                super::super::rustlyn_bindgen_system_io_path_has_extension_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(value)
        }

        pub fn is_path_fully_qualified(path: &ManagedString) -> Result<i32, Exception> {
            let mut exception_handle = 0;
            let value = unsafe {
                super::super::rustlyn_bindgen_system_io_path_is_path_fully_qualified_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(value)
        }

        pub fn is_path_rooted(path: &ManagedString) -> Result<i32, Exception> {
            let mut exception_handle = 0;
            let value = unsafe {
                super::super::rustlyn_bindgen_system_io_path_is_path_rooted_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };
            Exception::from_handle(exception_handle)?;
            Ok(value)
        }
    }
}

pub struct ManagedString {
    handle: i32,
}

impl ManagedString {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub unsafe fn from_borrowed_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn into_handle(self) -> i32 {
        self.handle
    }

    pub fn from_utf8_parts(value_ptr: *const u8, value_len: i64) -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_string_from_utf8(
                value_ptr,
                value_len,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(Self::from_handle(object_handle))
    }

    pub fn len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_string_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn utf8_len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_string_utf8_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn copy_utf8_into(&self, buffer: &mut [u8]) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let written = unsafe {
            rustlyn_bindgen_system_string_copy_utf8(
                self.handle,
                buffer.as_mut_ptr(),
                buffer.len() as i64,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(written)
    }

    pub fn contains_utf8_parts(&self, needle_ptr: *const u8, needle_len: i64) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let contains = unsafe {
            rustlyn_bindgen_system_string_contains_utf8(
                self.handle,
                needle_ptr,
                needle_len,
                StringComparison::Ordinal.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(contains != 0)
    }

    pub fn contains_utf8_parts_with_comparison(&self, needle_ptr: *const u8, needle_len: i64, comparison: StringComparison) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let contains = unsafe {
            rustlyn_bindgen_system_string_contains_utf8(
                self.handle,
                needle_ptr,
                needle_len,
                comparison.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(contains != 0)
    }

    pub fn contains(&self, needle: &ManagedString) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let contains = unsafe {
            rustlyn_bindgen_system_string_contains_string(
                self.handle,
                needle.handle(),
                StringComparison::Ordinal.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(contains != 0)
    }

    pub fn contains_with_comparison(&self, needle: &ManagedString, comparison: StringComparison) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let contains = unsafe {
            rustlyn_bindgen_system_string_contains_string(
                self.handle,
                needle.handle(),
                comparison.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(contains != 0)
    }

    pub fn index_of(&self, value: &ManagedString) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let index = unsafe {
            rustlyn_bindgen_system_string_index_of_string(
                self.handle,
                value.handle(),
                StringComparison::Ordinal.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(index)
    }

    pub fn index_of_with_comparison(&self, value: &ManagedString, comparison: StringComparison) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let index = unsafe {
            rustlyn_bindgen_system_string_index_of_string(
                self.handle,
                value.handle(),
                comparison.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(index)
    }

    pub fn starts_with(&self, value: &ManagedString) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let starts = unsafe {
            rustlyn_bindgen_system_string_starts_with_string(
                self.handle,
                value.handle(),
                StringComparison::Ordinal.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(starts != 0)
    }

    pub fn starts_with_comparison(&self, value: &ManagedString, comparison: StringComparison) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let starts = unsafe {
            rustlyn_bindgen_system_string_starts_with_string(
                self.handle,
                value.handle(),
                comparison.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(starts != 0)
    }

    pub fn ends_with(&self, value: &ManagedString) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let ends = unsafe {
            rustlyn_bindgen_system_string_ends_with_string(
                self.handle,
                value.handle(),
                StringComparison::Ordinal.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ends != 0)
    }

    pub fn ends_with_comparison(&self, value: &ManagedString, comparison: StringComparison) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let ends = unsafe {
            rustlyn_bindgen_system_string_ends_with_string(
                self.handle,
                value.handle(),
                comparison.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ends != 0)
    }

    pub fn split(&self, separator: &ManagedString, options: StringSplitOptions) -> Result<ManagedStringArray, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_string_split_string_options(
                self.handle,
                separator.handle(),
                options.as_i32(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedStringArray::from_handle(object_handle))
    }

    pub fn substring(&self, start_index: i32, length: i32) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_string_substring_i32_i32(
                self.handle,
                start_index,
                length,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn replace(&self, old_value: &ManagedString, new_value: &ManagedString) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_string_replace_string_string(
                self.handle,
                old_value.handle(),
                new_value.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub struct ManagedStringArray {
    handle: i32,
}

impl ManagedStringArray {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn from_strings(first: &ManagedString, second: &ManagedString, third: &ManagedString) -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_string_array_from_strings(
                first.handle(),
                second.handle(),
                third.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(Self::from_handle(object_handle))
    }

    pub fn len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_string_array_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn get(&self, index: i32) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_string_array_get(
                self.handle,
                index,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub struct ManagedIntArray {
    handle: i32,
}

impl ManagedIntArray {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn from_i32_triplet(first: i32, second: i32, third: i32) -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_int_array_from_i32_triplet(
                first,
                second,
                third,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(Self::from_handle(object_handle))
    }

    pub fn len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_int_array_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn get(&self, index: i32) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            rustlyn_bindgen_system_int_array_get(
                self.handle,
                index,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn copy_into(&self, buffer: &mut [i32]) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let written = unsafe {
            rustlyn_bindgen_system_int_array_copy(
                self.handle,
                buffer.as_mut_ptr(),
                buffer.len() as i64,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(written)
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub struct ManagedByteArray {
    handle: i32,
}

impl ManagedByteArray {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn from_u8_triplet(first: u8, second: u8, third: u8) -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_byte_array_from_u8_triplet(
                first as i32,
                second as i32,
                third as i32,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(Self::from_handle(object_handle))
    }

    pub fn len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rustlyn_bindgen_system_byte_array_len(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn get(&self, index: i32) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let value = unsafe {
            rustlyn_bindgen_system_byte_array_get(
                self.handle,
                index,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(value)
    }

    pub fn copy_into(&self, buffer: &mut [u8]) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let written = unsafe {
            rustlyn_bindgen_system_byte_array_copy(
                self.handle,
                buffer.as_mut_ptr(),
                buffer.len() as i64,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(written)
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub struct ManagedTimeSpan {
    handle: i32,
}

impl ManagedTimeSpan {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn ticks(&self) -> Result<i64, Exception> {
        let mut exception_handle = 0;
        let ticks = unsafe {
            rustlyn_bindgen_system_time_span_ticks(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ticks)
    }

    pub fn total_milliseconds(&self) -> Result<f64, Exception> {
        let mut exception_handle = 0;
        let milliseconds = unsafe {
            rustlyn_bindgen_system_time_span_total_milliseconds(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(milliseconds)
    }

    pub fn to_string(&self) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_time_span_to_string(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub struct ManagedDateTimeOffset {
    handle: i32,
}

impl ManagedDateTimeOffset {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn to_unix_time_milliseconds(&self) -> Result<i64, Exception> {
        let mut exception_handle = 0;
        let milliseconds = unsafe {
            rustlyn_bindgen_system_date_time_offset_to_unix_time_milliseconds(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(milliseconds)
    }

    pub fn to_string(&self) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_date_time_offset_to_string(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}

pub struct ManagedGuid {
    handle: i32,
}

impl ManagedGuid {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn to_string(&self) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            rustlyn_bindgen_system_guid_to_string(
                self.handle,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe {
            rustlyn_bindgen_system_object_release(
                self.handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(())
    }
}