// this file is automatically generated
// Copyright 2020 SourceGear
#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_unsafe)]
#![allow(unused_imports)]
#![allow(unused_parens)]

extern {
    fn __drop_handle(self_h : i64);
    fn __copy_handle(self_h : i64) -> i64;
}

// System
pub mod System {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.ComponentModel
pub mod ComponentModel {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.ComponentModel.Win32Exception
// from Microsoft.Win32.Primitives
#[derive(Debug)]
pub struct Win32Exception {
    h : i64
}

impl ::sgrust_core::SGRustValue for Win32Exception {
    fn get_type_handle() -> i64 {
        extern {
            fn System_ComponentModel_Win32Exception_get_type_handle() -> i64;
        }
        unsafe {
            return System_ComponentModel_Win32Exception_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for Win32Exception {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl Win32Exception {

    // .ctor()
    pub fn ctor__0() -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_ctor__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let h = System_ComponentModel_Win32Exception_ctor__0(&mut __thrown);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.Int32)
    pub fn ctor__1__i32(_error : i32) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_ctor__1__i32(thrown : *mut i64, _error : i32) -> i64;
        }
        unsafe {
            let h = System_ComponentModel_Win32Exception_ctor__1__i32(&mut __thrown, _error);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.Int32, System.String)
    pub fn ctor__2__i32_String(_error : i32, _message : &::System_Runtime::System::String) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_ctor__2__i32_String(thrown : *mut i64, _error : i32, _message : i64) -> i64;
        }
        unsafe {
            let h = System_ComponentModel_Win32Exception_ctor__2__i32_String(&mut __thrown, _error, _message.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String)
    pub fn ctor__1__String(_message : &::System_Runtime::System::String) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_ctor__1__String(thrown : *mut i64, _message : i64) -> i64;
        }
        unsafe {
            let h = System_ComponentModel_Win32Exception_ctor__1__String(&mut __thrown, _message.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String, System.Exception)
    pub fn ctor__2__String_Exception(_message : &::System_Runtime::System::String, _innerException : &::System_Runtime::System::Exception) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_ctor__2__String_Exception(thrown : *mut i64, _message : i64, _innerException : i64) -> i64;
        }
        unsafe {
            let h = System_ComponentModel_Win32Exception_ctor__2__String_Exception(&mut __thrown, _message.get_handle(), _innerException.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Int32 get_NativeErrorCode()
    pub fn i32__get_NativeErrorCode__0(&self) -> Result<i32,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_i32__get_NativeErrorCode__0(thrown : *mut i64, self_h : i64) -> i32;
        }
        unsafe {
            let __return = System_ComponentModel_Win32Exception_i32__get_NativeErrorCode__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
    pub fn void__GetObjectData__2__SerializationInfo_StreamingContext(&self, _info : &::System_Runtime::System::Runtime::Serialization::SerializationInfo, _context : &::System_Runtime::System::Runtime::Serialization::StreamingContext)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_void__GetObjectData__2__SerializationInfo_StreamingContext(thrown : *mut i64, self_h : i64, _info : i64, _context : i64);
        }
        unsafe {
            System_ComponentModel_Win32Exception_void__GetObjectData__2__SerializationInfo_StreamingContext(&mut __thrown, self.get_handle(), _info.get_handle(), _context.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.String ToString()
    pub fn String__ToString__0(&self) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_ComponentModel_Win32Exception_String__ToString__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_ComponentModel_Win32Exception_String__ToString__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Runtime::InteropServices::ExternalException> for Win32Exception {
    fn into(self) -> ::System_Runtime::System::Runtime::InteropServices::ExternalException {
        unsafe { ::System_Runtime::System::Runtime::InteropServices::ExternalException::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::SystemException> for Win32Exception {
    fn into(self) -> ::System_Runtime::System::SystemException {
        unsafe { ::System_Runtime::System::SystemException::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Exception> for Win32Exception {
    fn into(self) -> ::System_Runtime::System::Exception {
        unsafe { ::System_Runtime::System::Exception::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for Win32Exception {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Runtime::Serialization::ISerializable> for Win32Exception {
    fn into(self) -> ::System_Runtime::System::Runtime::Serialization::ISerializable {
        extern {
            fn System_ComponentModel_Win32Exception_to_ISerializable(self_h : i64) -> i64;
        }
        unsafe {
            let h = System_ComponentModel_Win32Exception_to_ISerializable(self.get_handle());
            return SGRustObjectHandle::from_handle(h);
        }
    }
}

pub trait System_ComponentModel_Win32Exception_overload_i32_get_NativeErrorCode_t_m<TA> {
    fn get_NativeErrorCode(&self, args : TA) -> Result<i32,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_get_NativeErrorCode_r_m<> {
    fn get_NativeErrorCode(&self, ) -> Result<i32,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_i32_get_NativeErrorCode_0_m<> {
    fn get_NativeErrorCode_0(&self, ) -> Result<i32,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_void_GetObjectData_t_m<TA> {
    fn GetObjectData(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_GetObjectData_r_m<TA1,TA2> {
    fn GetObjectData(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_void_GetObjectData_2_m<TA1,TA2> {
    fn GetObjectData_2(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_String_ToString_t_m<TA> {
    fn ToString(&self, args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_ToString_r_m<> {
    fn ToString(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_String_ToString_0_m<> {
    fn ToString_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_0_f<> {
    fn ctor_0() -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_1_f<TA1> {
    fn ctor_1(p1 : TA1) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_2_f<TA1,TA2> {
    fn ctor_2(p1 : TA1,p2 : TA2) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception>;
}
pub trait System_ComponentModel_Win32Exception_overload_NativeErrorCode_s_m<> {
    fn NativeErrorCode(&self, ) -> Result<i32,::System_Runtime::System::Exception>;
}
impl System_ComponentModel_Win32Exception_overload_get_NativeErrorCode_r_m<> for Win32Exception {
    fn get_NativeErrorCode(&self, ) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__get_NativeErrorCode__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_i32_get_NativeErrorCode_0_m<> for Win32Exception {
    fn get_NativeErrorCode_0(&self, ) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__get_NativeErrorCode__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_i32_get_NativeErrorCode_t_m<()> for Win32Exception {
    fn get_NativeErrorCode(&self, _a : ()) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__get_NativeErrorCode__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_GetObjectData_r_m<&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext> for Win32Exception {
    fn GetObjectData(&self, p1 : &::System_Runtime::System::Runtime::Serialization::SerializationInfo,p2 : &::System_Runtime::System::Runtime::Serialization::StreamingContext)-> Result<(),::System_Runtime::System::Exception> {
        self.void__GetObjectData__2__SerializationInfo_StreamingContext(p1,p2)
    }
}
impl System_ComponentModel_Win32Exception_overload_void_GetObjectData_2_m<&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext> for Win32Exception {
    fn GetObjectData_2(&self, p1 : &::System_Runtime::System::Runtime::Serialization::SerializationInfo,p2 : &::System_Runtime::System::Runtime::Serialization::StreamingContext)-> Result<(),::System_Runtime::System::Exception> {
        self.void__GetObjectData__2__SerializationInfo_StreamingContext(p1,p2)
    }
}
impl System_ComponentModel_Win32Exception_overload_void_GetObjectData_t_m<(&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext)> for Win32Exception {
    fn GetObjectData(&self, a : (&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext))-> Result<(),::System_Runtime::System::Exception> {
        self.void__GetObjectData__2__SerializationInfo_StreamingContext(a.0,a.1)
    }
}
impl System_ComponentModel_Win32Exception_overload_ToString_r_m<> for Win32Exception {
    fn ToString(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__ToString__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_String_ToString_0_m<> for Win32Exception {
    fn ToString_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__ToString__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_String_ToString_t_m<()> for Win32Exception {
    fn ToString(&self, _a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__ToString__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_0_f<> for Win32Exception {
    fn ctor_0() -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f<()> for Win32Exception {
    fn ctor(_a : ()) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_1_f<i32> for Win32Exception {
    fn ctor_1(p1 : i32) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__1__i32(p1)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f<(i32,)> for Win32Exception {
    fn ctor(a : (i32,)) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__1__i32(a.0,)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_1_f<&::System_Runtime::System::String> for Win32Exception {
    fn ctor_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f<(&::System_Runtime::System::String,)> for Win32Exception {
    fn ctor(a : (&::System_Runtime::System::String,)) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__1__String(a.0,)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_2_f<i32,&::System_Runtime::System::String> for Win32Exception {
    fn ctor_2(p1 : i32,p2 : &::System_Runtime::System::String) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__2__i32_String(p1,p2)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f<(i32,&::System_Runtime::System::String)> for Win32Exception {
    fn ctor(a : (i32,&::System_Runtime::System::String)) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__2__i32_String(a.0,a.1)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_2_f<&::System_Runtime::System::String,&::System_Runtime::System::Exception> for Win32Exception {
    fn ctor_2(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Exception) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__2__String_Exception(p1,p2)
    }
}
impl System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f<(&::System_Runtime::System::String,&::System_Runtime::System::Exception)> for Win32Exception {
    fn ctor(a : (&::System_Runtime::System::String,&::System_Runtime::System::Exception)) -> Result<crate::System::ComponentModel::Win32Exception,::System_Runtime::System::Exception> {
        Self::ctor__2__String_Exception(a.0,a.1)
    }
}
impl System_ComponentModel_Win32Exception_overload_NativeErrorCode_s_m<> for Win32Exception {
    fn NativeErrorCode(&self, ) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__get_NativeErrorCode__0()
    }
}

} // System.ComponentModel

} // System

pub mod overloads_with_count {
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_i32_get_NativeErrorCode_0_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_void_GetObjectData_2_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_String_ToString_0_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_0_f;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_1_f;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_2_f;
}
pub mod overloads_with_tuple {
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_i32_get_NativeErrorCode_t_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_void_GetObjectData_t_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_String_ToString_t_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_Win32Exception_ctor_t_f;
}
pub mod overloads_special {
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_NativeErrorCode_s_m;
}
pub mod overloads_risky {
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_get_NativeErrorCode_r_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_GetObjectData_r_m;
pub use crate::System::ComponentModel::System_ComponentModel_Win32Exception_overload_ToString_r_m;
}

