// this file is automatically generated
// Copyright 2020 SourceGear
#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_unsafe)]
#![allow(unused_imports)]
#![allow(unused_parens)]

extern {
    fn __drop_handle(self_h : i64);
    fn __copy_handle(self_h : i64) -> i64;
}

// System
pub mod System {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Xml
pub mod Xml {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Xml.XPath
pub mod XPath {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Xml.XPath.XPathDocument
// from System.Xml.XPath
#[derive(Debug)]
pub struct XPathDocument {
    h : i64
}

impl ::sgrust_core::SGRustValue for XPathDocument {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Xml_XPath_XPathDocument_get_type_handle() -> i64;
        }
        unsafe {
            return System_Xml_XPath_XPathDocument_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for XPathDocument {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl XPathDocument {

    // .ctor(System.IO.Stream)
    pub fn ctor__1__Stream(_stream : &::System_Runtime::System::IO::Stream) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_ctor__1__Stream(thrown : *mut i64, _stream : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_ctor__1__Stream(&mut __thrown, _stream.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.IO.TextReader)
    pub fn ctor__1__TextReader(_textReader : &::System_Runtime::System::IO::TextReader) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_ctor__1__TextReader(thrown : *mut i64, _textReader : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_ctor__1__TextReader(&mut __thrown, _textReader.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String)
    pub fn ctor__1__String(_uri : &::System_Runtime::System::String) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_ctor__1__String(thrown : *mut i64, _uri : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_ctor__1__String(&mut __thrown, _uri.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String, System.Xml.XmlSpace)
    pub fn ctor__2__String_XmlSpace(_uri : &::System_Runtime::System::String, _space : ::System_Xml_ReaderWriter::System::Xml::XmlSpace) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_ctor__2__String_XmlSpace(thrown : *mut i64, _uri : i64, _space : i32) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_ctor__2__String_XmlSpace(&mut __thrown, _uri.get_handle(), _space.get_value());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.Xml.XmlReader)
    pub fn ctor__1__XmlReader(_reader : &::System_Xml_ReaderWriter::System::Xml::XmlReader) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_ctor__1__XmlReader(thrown : *mut i64, _reader : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_ctor__1__XmlReader(&mut __thrown, _reader.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.Xml.XmlReader, System.Xml.XmlSpace)
    pub fn ctor__2__XmlReader_XmlSpace(_reader : &::System_Xml_ReaderWriter::System::Xml::XmlReader, _space : ::System_Xml_ReaderWriter::System::Xml::XmlSpace) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_ctor__2__XmlReader_XmlSpace(thrown : *mut i64, _reader : i64, _space : i32) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_ctor__2__XmlReader_XmlSpace(&mut __thrown, _reader.get_handle(), _space.get_value());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Xml.XPath.XPathNavigator CreateNavigator()
    pub fn XPathNavigator__CreateNavigator__0(&self) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathDocument_XPathNavigator__CreateNavigator__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Xml_XPath_XPathDocument_XPathNavigator__CreateNavigator__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Object> for XPathDocument {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Xml_ReaderWriter::System::Xml::XPath::IXPathNavigable> for XPathDocument {
    fn into(self) -> ::System_Xml_ReaderWriter::System::Xml::XPath::IXPathNavigable {
        extern {
            fn System_Xml_XPath_XPathDocument_to_IXPathNavigable(self_h : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathDocument_to_IXPathNavigable(self.get_handle());
            return SGRustObjectHandle::from_handle(h);
        }
    }
}

pub trait System_Xml_XPath_XPathDocument_overload_XPathNavigator_CreateNavigator_t_m<TA> {
    fn CreateNavigator(&self, args : TA) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathDocument_overload_CreateNavigator_r_m<> {
    fn CreateNavigator(&self, ) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathDocument_overload_XPathNavigator_CreateNavigator_0_m<> {
    fn CreateNavigator_0(&self, ) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_1_f<TA1> {
    fn ctor_1(p1 : TA1) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_2_f<TA1,TA2> {
    fn ctor_2(p1 : TA1,p2 : TA2) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception>;
}
impl System_Xml_XPath_XPathDocument_overload_CreateNavigator_r_m<> for XPathDocument {
    fn CreateNavigator(&self, ) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception> {
        self.XPathNavigator__CreateNavigator__0()
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathNavigator_CreateNavigator_0_m<> for XPathDocument {
    fn CreateNavigator_0(&self, ) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception> {
        self.XPathNavigator__CreateNavigator__0()
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathNavigator_CreateNavigator_t_m<()> for XPathDocument {
    fn CreateNavigator(&self, _a : ()) -> Result<::System_Xml_ReaderWriter::System::Xml::XPath::XPathNavigator,::System_Runtime::System::Exception> {
        self.XPathNavigator__CreateNavigator__0()
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_1_f<&::System_Runtime::System::IO::Stream> for XPathDocument {
    fn ctor_1(p1 : &::System_Runtime::System::IO::Stream) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__Stream(p1)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<(&::System_Runtime::System::IO::Stream,)> for XPathDocument {
    fn ctor(a : (&::System_Runtime::System::IO::Stream,)) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__Stream(a.0,)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_1_f<&::System_Runtime::System::IO::TextReader> for XPathDocument {
    fn ctor_1(p1 : &::System_Runtime::System::IO::TextReader) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__TextReader(p1)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<(&::System_Runtime::System::IO::TextReader,)> for XPathDocument {
    fn ctor(a : (&::System_Runtime::System::IO::TextReader,)) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__TextReader(a.0,)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_1_f<&::System_Runtime::System::String> for XPathDocument {
    fn ctor_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<(&::System_Runtime::System::String,)> for XPathDocument {
    fn ctor(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__String(a.0,)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_1_f<&::System_Xml_ReaderWriter::System::Xml::XmlReader> for XPathDocument {
    fn ctor_1(p1 : &::System_Xml_ReaderWriter::System::Xml::XmlReader) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__XmlReader(p1)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<(&::System_Xml_ReaderWriter::System::Xml::XmlReader,)> for XPathDocument {
    fn ctor(a : (&::System_Xml_ReaderWriter::System::Xml::XmlReader,)) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__1__XmlReader(a.0,)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_2_f<&::System_Runtime::System::String,::System_Xml_ReaderWriter::System::Xml::XmlSpace> for XPathDocument {
    fn ctor_2(p1 : &::System_Runtime::System::String,p2 : ::System_Xml_ReaderWriter::System::Xml::XmlSpace) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__2__String_XmlSpace(p1,p2)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<(&::System_Runtime::System::String,::System_Xml_ReaderWriter::System::Xml::XmlSpace)> for XPathDocument {
    fn ctor(a : (&::System_Runtime::System::String,::System_Xml_ReaderWriter::System::Xml::XmlSpace)) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__2__String_XmlSpace(a.0,a.1)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_2_f<&::System_Xml_ReaderWriter::System::Xml::XmlReader,::System_Xml_ReaderWriter::System::Xml::XmlSpace> for XPathDocument {
    fn ctor_2(p1 : &::System_Xml_ReaderWriter::System::Xml::XmlReader,p2 : ::System_Xml_ReaderWriter::System::Xml::XmlSpace) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__2__XmlReader_XmlSpace(p1,p2)
    }
}
impl System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f<(&::System_Xml_ReaderWriter::System::Xml::XmlReader,::System_Xml_ReaderWriter::System::Xml::XmlSpace)> for XPathDocument {
    fn ctor(a : (&::System_Xml_ReaderWriter::System::Xml::XmlReader,::System_Xml_ReaderWriter::System::Xml::XmlSpace)) -> Result<crate::System::Xml::XPath::XPathDocument,::System_Runtime::System::Exception> {
        Self::ctor__2__XmlReader_XmlSpace(a.0,a.1)
    }
}

// System.Xml.XPath.XPathException
// from System.Xml.XPath
#[derive(Debug)]
pub struct XPathException {
    h : i64
}

impl ::sgrust_core::SGRustValue for XPathException {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Xml_XPath_XPathException_get_type_handle() -> i64;
        }
        unsafe {
            return System_Xml_XPath_XPathException_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for XPathException {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl XPathException {

    // .ctor()
    pub fn ctor__0() -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathException_ctor__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathException_ctor__0(&mut __thrown);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String)
    pub fn ctor__1__String(_message : &::System_Runtime::System::String) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathException_ctor__1__String(thrown : *mut i64, _message : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathException_ctor__1__String(&mut __thrown, _message.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // .ctor(System.String, System.Exception)
    pub fn ctor__2__String_Exception(_message : &::System_Runtime::System::String, _innerException : &::System_Runtime::System::Exception) -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathException_ctor__2__String_Exception(thrown : *mut i64, _message : i64, _innerException : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathException_ctor__2__String_Exception(&mut __thrown, _message.get_handle(), _innerException.get_handle());
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.String get_Message()
    pub fn String__get_Message__0(&self) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathException_String__get_Message__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Xml_XPath_XPathException_String__get_Message__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Void GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
    pub fn void__GetObjectData__2__SerializationInfo_StreamingContext(&self, _info : &::System_Runtime::System::Runtime::Serialization::SerializationInfo, _context : &::System_Runtime::System::Runtime::Serialization::StreamingContext)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Xml_XPath_XPathException_void__GetObjectData__2__SerializationInfo_StreamingContext(thrown : *mut i64, self_h : i64, _info : i64, _context : i64);
        }
        unsafe {
            System_Xml_XPath_XPathException_void__GetObjectData__2__SerializationInfo_StreamingContext(&mut __thrown, self.get_handle(), _info.get_handle(), _context.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::SystemException> for XPathException {
    fn into(self) -> ::System_Runtime::System::SystemException {
        unsafe { ::System_Runtime::System::SystemException::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Exception> for XPathException {
    fn into(self) -> ::System_Runtime::System::Exception {
        unsafe { ::System_Runtime::System::Exception::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for XPathException {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Runtime::Serialization::ISerializable> for XPathException {
    fn into(self) -> ::System_Runtime::System::Runtime::Serialization::ISerializable {
        extern {
            fn System_Xml_XPath_XPathException_to_ISerializable(self_h : i64) -> i64;
        }
        unsafe {
            let h = System_Xml_XPath_XPathException_to_ISerializable(self.get_handle());
            return SGRustObjectHandle::from_handle(h);
        }
    }
}

pub trait System_Xml_XPath_XPathException_overload_String_get_Message_t_m<TA> {
    fn get_Message(&self, args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_get_Message_r_m<> {
    fn get_Message(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_String_get_Message_0_m<> {
    fn get_Message_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_void_GetObjectData_t_m<TA> {
    fn GetObjectData(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_GetObjectData_r_m<TA1,TA2> {
    fn GetObjectData(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_void_GetObjectData_2_m<TA1,TA2> {
    fn GetObjectData_2(&self, p1 : TA1,p2 : TA2)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_XPathException_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_XPathException_ctor_0_f<> {
    fn ctor_0() -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_XPathException_ctor_1_f<TA1> {
    fn ctor_1(p1 : TA1) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_XPathException_ctor_2_f<TA1,TA2> {
    fn ctor_2(p1 : TA1,p2 : TA2) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception>;
}
pub trait System_Xml_XPath_XPathException_overload_Message_s_m<> {
    fn Message(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
impl System_Xml_XPath_XPathException_overload_get_Message_r_m<> for XPathException {
    fn get_Message(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_Message__0()
    }
}
impl System_Xml_XPath_XPathException_overload_String_get_Message_0_m<> for XPathException {
    fn get_Message_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_Message__0()
    }
}
impl System_Xml_XPath_XPathException_overload_String_get_Message_t_m<()> for XPathException {
    fn get_Message(&self, _a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_Message__0()
    }
}
impl System_Xml_XPath_XPathException_overload_GetObjectData_r_m<&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext> for XPathException {
    fn GetObjectData(&self, p1 : &::System_Runtime::System::Runtime::Serialization::SerializationInfo,p2 : &::System_Runtime::System::Runtime::Serialization::StreamingContext)-> Result<(),::System_Runtime::System::Exception> {
        self.void__GetObjectData__2__SerializationInfo_StreamingContext(p1,p2)
    }
}
impl System_Xml_XPath_XPathException_overload_void_GetObjectData_2_m<&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext> for XPathException {
    fn GetObjectData_2(&self, p1 : &::System_Runtime::System::Runtime::Serialization::SerializationInfo,p2 : &::System_Runtime::System::Runtime::Serialization::StreamingContext)-> Result<(),::System_Runtime::System::Exception> {
        self.void__GetObjectData__2__SerializationInfo_StreamingContext(p1,p2)
    }
}
impl System_Xml_XPath_XPathException_overload_void_GetObjectData_t_m<(&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext)> for XPathException {
    fn GetObjectData(&self, a : (&::System_Runtime::System::Runtime::Serialization::SerializationInfo,&::System_Runtime::System::Runtime::Serialization::StreamingContext))-> Result<(),::System_Runtime::System::Exception> {
        self.void__GetObjectData__2__SerializationInfo_StreamingContext(a.0,a.1)
    }
}
impl System_Xml_XPath_XPathException_overload_XPathException_ctor_0_f<> for XPathException {
    fn ctor_0() -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Xml_XPath_XPathException_overload_XPathException_ctor_t_f<()> for XPathException {
    fn ctor(_a : ()) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Xml_XPath_XPathException_overload_XPathException_ctor_1_f<&::System_Runtime::System::String> for XPathException {
    fn ctor_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception> {
        Self::ctor__1__String(p1)
    }
}
impl System_Xml_XPath_XPathException_overload_XPathException_ctor_t_f<(&::System_Runtime::System::String,)> for XPathException {
    fn ctor(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception> {
        Self::ctor__1__String(a.0,)
    }
}
impl System_Xml_XPath_XPathException_overload_XPathException_ctor_2_f<&::System_Runtime::System::String,&::System_Runtime::System::Exception> for XPathException {
    fn ctor_2(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::Exception) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception> {
        Self::ctor__2__String_Exception(p1,p2)
    }
}
impl System_Xml_XPath_XPathException_overload_XPathException_ctor_t_f<(&::System_Runtime::System::String,&::System_Runtime::System::Exception)> for XPathException {
    fn ctor(a : (&::System_Runtime::System::String,&::System_Runtime::System::Exception)) -> Result<crate::System::Xml::XPath::XPathException,::System_Runtime::System::Exception> {
        Self::ctor__2__String_Exception(a.0,a.1)
    }
}
impl System_Xml_XPath_XPathException_overload_Message_s_m<> for XPathException {
    fn Message(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_Message__0()
    }
}

} // System.Xml.XPath

} // System.Xml

} // System

pub mod overloads_with_count {
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathDocument_overload_XPathNavigator_CreateNavigator_0_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_1_f;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_2_f;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_String_get_Message_0_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_void_GetObjectData_2_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_XPathException_ctor_0_f;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_XPathException_ctor_1_f;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_XPathException_ctor_2_f;
}
pub mod overloads_with_tuple {
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathDocument_overload_XPathNavigator_CreateNavigator_t_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathDocument_overload_XPathDocument_ctor_t_f;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_String_get_Message_t_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_void_GetObjectData_t_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_XPathException_ctor_t_f;
}
pub mod overloads_special {
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_Message_s_m;
}
pub mod overloads_risky {
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathDocument_overload_CreateNavigator_r_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_get_Message_r_m;
pub use crate::System::Xml::XPath::System_Xml_XPath_XPathException_overload_GetObjectData_r_m;
}

