namespace Rustlyn.Bindings;

public static class PowerShellRustBindingGenerator
{
    public static string GenerateCmdletModule()
        => GenerateCmdletModule(ExternalPackageBindingSurfaces.CreatePowerShellCmdletManifest());

    public static string GenerateCmdletModule(BindingManifestDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);
        var symbols = document.Bindings.Select(static binding => binding.Symbol).ToHashSet(StringComparer.Ordinal);
        foreach (var requiredSymbol in RequiredSymbols)
        {
            if (!symbols.Contains(requiredSymbol))
            {
                throw new InvalidOperationException($"PowerShell cmdlet binding manifest does not contain required symbol '{requiredSymbol}'.");
            }
        }

        return Template;
    }

    private static readonly string[] RequiredSymbols =
    [
        "rustlyn_bindgen_powershell_cmdlet_write_object_string",
        "rustlyn_bindgen_powershell_cmdlet_write_verbose_string",
        "rustlyn_bindgen_powershell_cmdlet_write_warning_string",
        "rustlyn_bindgen_powershell_cmdlet_write_error_string",
        "rustlyn_bindgen_powershell_cmdlet_get_parameter_string",
        "rustlyn_bindgen_powershell_cmdlet_should_process_string"
    ];

    private const string Template = """
// @generated by Rustlyn.Bindings. Do not edit by hand.
#![allow(dead_code)]

unsafe extern "C" {
    fn rustlyn_bindgen_powershell_cmdlet_write_object_string(
        cmdlet_context_handle: i32,
        value_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_powershell_cmdlet_write_verbose_string(
        cmdlet_context_handle: i32,
        message_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_powershell_cmdlet_write_warning_string(
        cmdlet_context_handle: i32,
        message_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_powershell_cmdlet_write_error_string(
        cmdlet_context_handle: i32,
        message_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_powershell_cmdlet_get_parameter_string(
        cmdlet_context_handle: i32,
        name_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_powershell_cmdlet_should_process_string(
        cmdlet_context_handle: i32,
        target_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Exception {
    handle: i32,
}

impl Exception {
    fn from_handle(handle: i32) -> Result<(), Self> {
        if handle == 0 {
            Ok(())
        } else {
            Err(Self { handle })
        }
    }
}

pub struct ManagedString {
    handle: i32,
}

impl ManagedString {
    pub unsafe fn from_borrowed_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CmdletContext {
    handle: i32,
}

impl CmdletContext {
    pub unsafe fn from_borrowed_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn write_object_string(&self, value: &ManagedString) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_powershell_cmdlet_write_object_string(
                self.handle,
                value.handle(),
                &mut exception_handle,
            );
        }
        Exception::from_handle(exception_handle)
    }

    pub fn write_verbose_string(&self, message: &ManagedString) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_powershell_cmdlet_write_verbose_string(
                self.handle,
                message.handle(),
                &mut exception_handle,
            );
        }
        Exception::from_handle(exception_handle)
    }

    pub fn write_warning_string(&self, message: &ManagedString) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_powershell_cmdlet_write_warning_string(
                self.handle,
                message.handle(),
                &mut exception_handle,
            );
        }
        Exception::from_handle(exception_handle)
    }

    pub fn write_error_string(&self, message: &ManagedString) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_powershell_cmdlet_write_error_string(
                self.handle,
                message.handle(),
                &mut exception_handle,
            );
        }
        Exception::from_handle(exception_handle)
    }

    pub fn get_parameter_string(&self, name: &ManagedString) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let result = unsafe {
            rustlyn_bindgen_powershell_cmdlet_get_parameter_string(
                self.handle,
                name.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(unsafe { ManagedString::from_borrowed_handle(result) })
    }

    pub fn should_process_string(&self, target: &ManagedString) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let result = unsafe {
            rustlyn_bindgen_powershell_cmdlet_should_process_string(
                self.handle,
                target.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(result != 0)
    }
}
""";
}
