// this file is automatically generated
// Copyright 2020 SourceGear
#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_unsafe)]
#![allow(unused_imports)]
#![allow(unused_parens)]

extern {
    fn __drop_handle(self_h : i64);
    fn __copy_handle(self_h : i64) -> i64;
}

// System
pub mod System {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Runtime
pub mod Runtime {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Runtime.InteropServices
pub mod InteropServices {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Runtime.InteropServices.Architecture
// from System.Runtime.InteropServices.RuntimeInformation
#[derive(Copy, Clone)]
pub struct Architecture {
    v : i32
}

impl ::sgrust_core::SGRustValue for Architecture {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_InteropServices_Architecture_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_InteropServices_Architecture_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.v as i64; }
    fn from_ffi(hndl : i64) -> Self { return Self { v : hndl as i32 } }
}

impl Architecture {
    pub fn from_value(val : i32) -> Architecture { return Architecture { v : val } }
    pub fn get_value(self) -> i32 { return self.v; }
}

impl Architecture {

    // field: System.Runtime.InteropServices.Architecture X86
    pub fn X86() -> crate::System::Runtime::InteropServices::Architecture {
        extern {
            fn System_Runtime_InteropServices_Architecture_X86() -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_Architecture_X86());
            return __return;
        }
    }
    // field: System.Runtime.InteropServices.Architecture X64
    pub fn X64() -> crate::System::Runtime::InteropServices::Architecture {
        extern {
            fn System_Runtime_InteropServices_Architecture_X64() -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_Architecture_X64());
            return __return;
        }
    }
    // field: System.Runtime.InteropServices.Architecture Arm
    pub fn Arm() -> crate::System::Runtime::InteropServices::Architecture {
        extern {
            fn System_Runtime_InteropServices_Architecture_Arm() -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_Architecture_Arm());
            return __return;
        }
    }
    // field: System.Runtime.InteropServices.Architecture Arm64
    pub fn Arm64() -> crate::System::Runtime::InteropServices::Architecture {
        extern {
            fn System_Runtime_InteropServices_Architecture_Arm64() -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_Architecture_Arm64());
            return __return;
        }
    }
    // field: System.Runtime.InteropServices.Architecture Wasm
    pub fn Wasm() -> crate::System::Runtime::InteropServices::Architecture {
        extern {
            fn System_Runtime_InteropServices_Architecture_Wasm() -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_Architecture_Wasm());
            return __return;
        }
    }
}


// System.Runtime.InteropServices.OSPlatform
// from System.Runtime.InteropServices.RuntimeInformation
// boxed value type
#[derive(Debug)]
pub struct OSPlatform {
    h : i64
}

impl ::sgrust_core::SGRustValue for OSPlatform {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Runtime_InteropServices_OSPlatform_get_type_handle() -> i64;
        }
        unsafe {
            return System_Runtime_InteropServices_OSPlatform_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for OSPlatform {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl OSPlatform {

    // [IsSpecialName] System.Runtime.InteropServices.OSPlatform get_FreeBSD()
    pub fn OSPlatform__get_FreeBSD__0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_OSPlatform__get_FreeBSD__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_OSPlatform_OSPlatform__get_FreeBSD__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Runtime.InteropServices.OSPlatform get_Linux()
    pub fn OSPlatform__get_Linux__0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_OSPlatform__get_Linux__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_OSPlatform_OSPlatform__get_Linux__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Runtime.InteropServices.OSPlatform get_OSX()
    pub fn OSPlatform__get_OSX__0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_OSPlatform__get_OSX__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_OSPlatform_OSPlatform__get_OSX__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Runtime.InteropServices.OSPlatform get_Windows()
    pub fn OSPlatform__get_Windows__0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_OSPlatform__get_Windows__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_OSPlatform_OSPlatform__get_Windows__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Runtime.InteropServices.OSPlatform Create(System.String)
    pub fn OSPlatform__Create__1__String(_osPlatform : &::System_Runtime::System::String) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_OSPlatform__Create__1__String(thrown : *mut i64, _osPlatform : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_OSPlatform_OSPlatform__Create__1__String(&mut __thrown, _osPlatform.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Boolean op_Equality(System.Runtime.InteropServices.OSPlatform, System.Runtime.InteropServices.OSPlatform)
    pub fn bool__op_Equality__2__OSPlatform_OSPlatform(_left : &crate::System::Runtime::InteropServices::OSPlatform, _right : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_bool__op_Equality__2__OSPlatform_OSPlatform(thrown : *mut i64, _left : i64, _right : i64) -> i32;
        }
        unsafe {
            let __return = (System_Runtime_InteropServices_OSPlatform_bool__op_Equality__2__OSPlatform_OSPlatform(&mut __thrown, _left.get_handle(), _right.get_handle())) != 0;
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Boolean op_Inequality(System.Runtime.InteropServices.OSPlatform, System.Runtime.InteropServices.OSPlatform)
    pub fn bool__op_Inequality__2__OSPlatform_OSPlatform(_left : &crate::System::Runtime::InteropServices::OSPlatform, _right : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_bool__op_Inequality__2__OSPlatform_OSPlatform(thrown : *mut i64, _left : i64, _right : i64) -> i32;
        }
        unsafe {
            let __return = (System_Runtime_InteropServices_OSPlatform_bool__op_Inequality__2__OSPlatform_OSPlatform(&mut __thrown, _left.get_handle(), _right.get_handle())) != 0;
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Boolean Equals(System.Object)
    pub fn bool__Equals__1__Object(&self, _obj : &::System_Runtime::System::Object) -> Result<bool,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_bool__Equals__1__Object(thrown : *mut i64, self_h : i64, _obj : i64) -> i32;
        }
        unsafe {
            let __return = (System_Runtime_InteropServices_OSPlatform_bool__Equals__1__Object(&mut __thrown, self.get_handle(), _obj.get_handle())) != 0;
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Boolean Equals(System.Runtime.InteropServices.OSPlatform)
    pub fn bool__Equals__1__OSPlatform(&self, _other : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_bool__Equals__1__OSPlatform(thrown : *mut i64, self_h : i64, _other : i64) -> i32;
        }
        unsafe {
            let __return = (System_Runtime_InteropServices_OSPlatform_bool__Equals__1__OSPlatform(&mut __thrown, self.get_handle(), _other.get_handle())) != 0;
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Int32 GetHashCode()
    pub fn i32__GetHashCode__0(&self) -> Result<i32,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_i32__GetHashCode__0(thrown : *mut i64, self_h : i64) -> i32;
        }
        unsafe {
            let __return = System_Runtime_InteropServices_OSPlatform_i32__GetHashCode__0(&mut __thrown, self.get_handle());
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.String ToString()
    pub fn String__ToString__0(&self) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_OSPlatform_String__ToString__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_OSPlatform_String__ToString__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::ValueType> for OSPlatform {
    fn into(self) -> ::System_Runtime::System::ValueType {
        unsafe { ::System_Runtime::System::ValueType::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

impl Into<::System_Runtime::System::Object> for OSPlatform {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_FreeBSD_t_f<TA> {
    fn get_FreeBSD(args : TA) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_get_FreeBSD_r_f<> {
    fn get_FreeBSD() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_FreeBSD_0_f<> {
    fn get_FreeBSD_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Linux_t_f<TA> {
    fn get_Linux(args : TA) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_get_Linux_r_f<> {
    fn get_Linux() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Linux_0_f<> {
    fn get_Linux_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_OSX_t_f<TA> {
    fn get_OSX(args : TA) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_get_OSX_r_f<> {
    fn get_OSX() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_OSX_0_f<> {
    fn get_OSX_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Windows_t_f<TA> {
    fn get_Windows(args : TA) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_get_Windows_r_f<> {
    fn get_Windows() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Windows_0_f<> {
    fn get_Windows_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_Create_t_f<TA> {
    fn Create(args : TA) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_Create_r_f<TA1> {
    fn Create(p1 : TA1) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_Create_1_f<TA1> {
    fn Create_1(p1 : TA1) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_t_m<TA> {
    fn Equals(&self, args : TA) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_Equals_r_m<TA1> {
    fn Equals(&self, p1 : TA1) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_1_m<TA1> {
    fn Equals_1(&self, p1 : TA1) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_i32_GetHashCode_t_m<TA> {
    fn GetHashCode(&self, args : TA) -> Result<i32,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_GetHashCode_r_m<> {
    fn GetHashCode(&self, ) -> Result<i32,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_i32_GetHashCode_0_m<> {
    fn GetHashCode_0(&self, ) -> Result<i32,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_bool_op_Equality_t_f<TA> {
    fn op_Equality(args : TA) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_op_Equality_r_f<TA1,TA2> {
    fn op_Equality(p1 : TA1,p2 : TA2) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_bool_op_Equality_2_f<TA1,TA2> {
    fn op_Equality_2(p1 : TA1,p2 : TA2) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_bool_op_Inequality_t_f<TA> {
    fn op_Inequality(args : TA) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_op_Inequality_r_f<TA1,TA2> {
    fn op_Inequality(p1 : TA1,p2 : TA2) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_bool_op_Inequality_2_f<TA1,TA2> {
    fn op_Inequality_2(p1 : TA1,p2 : TA2) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_String_ToString_t_m<TA> {
    fn ToString(&self, args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_ToString_r_m<> {
    fn ToString(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_String_ToString_0_m<> {
    fn ToString_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_FreeBSD_s_f<> {
    fn FreeBSD() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_Linux_s_f<> {
    fn Linux() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_OSX_s_f<> {
    fn OSX() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_OSPlatform_overload_Windows_s_f<> {
    fn Windows() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception>;
}
impl System_Runtime_InteropServices_OSPlatform_overload_get_FreeBSD_r_f<> for OSPlatform {
    fn get_FreeBSD() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_FreeBSD__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_FreeBSD_0_f<> for OSPlatform {
    fn get_FreeBSD_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_FreeBSD__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_FreeBSD_t_f<()> for OSPlatform {
    fn get_FreeBSD(_a : ()) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_FreeBSD__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_get_Linux_r_f<> for OSPlatform {
    fn get_Linux() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Linux__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Linux_0_f<> for OSPlatform {
    fn get_Linux_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Linux__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Linux_t_f<()> for OSPlatform {
    fn get_Linux(_a : ()) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Linux__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_get_OSX_r_f<> for OSPlatform {
    fn get_OSX() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_OSX__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_OSX_0_f<> for OSPlatform {
    fn get_OSX_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_OSX__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_OSX_t_f<()> for OSPlatform {
    fn get_OSX(_a : ()) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_OSX__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_get_Windows_r_f<> for OSPlatform {
    fn get_Windows() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Windows__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Windows_0_f<> for OSPlatform {
    fn get_Windows_0() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Windows__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Windows_t_f<()> for OSPlatform {
    fn get_Windows(_a : ()) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Windows__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_Create_r_f<&::System_Runtime::System::String> for OSPlatform {
    fn Create(p1 : &::System_Runtime::System::String) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__Create__1__String(p1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_Create_1_f<&::System_Runtime::System::String> for OSPlatform {
    fn Create_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__Create__1__String(p1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_Create_t_f<(&::System_Runtime::System::String,)> for OSPlatform {
    fn Create(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__Create__1__String(a.0,)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_Equals_r_m<&::System_Runtime::System::Object> for OSPlatform {
    fn Equals(&self, p1 : &::System_Runtime::System::Object) -> Result<bool,::System_Runtime::System::Exception> {
        self.bool__Equals__1__Object(p1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_1_m<&::System_Runtime::System::Object> for OSPlatform {
    fn Equals_1(&self, p1 : &::System_Runtime::System::Object) -> Result<bool,::System_Runtime::System::Exception> {
        self.bool__Equals__1__Object(p1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_t_m<(&::System_Runtime::System::Object,)> for OSPlatform {
    fn Equals(&self, a : (&::System_Runtime::System::Object,)) -> Result<bool,::System_Runtime::System::Exception> {
        self.bool__Equals__1__Object(a.0,)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_Equals_r_m<&crate::System::Runtime::InteropServices::OSPlatform> for OSPlatform {
    fn Equals(&self, p1 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        self.bool__Equals__1__OSPlatform(p1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_1_m<&crate::System::Runtime::InteropServices::OSPlatform> for OSPlatform {
    fn Equals_1(&self, p1 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        self.bool__Equals__1__OSPlatform(p1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_t_m<(&crate::System::Runtime::InteropServices::OSPlatform,)> for OSPlatform {
    fn Equals(&self, a : (&crate::System::Runtime::InteropServices::OSPlatform,)) -> Result<bool,::System_Runtime::System::Exception> {
        self.bool__Equals__1__OSPlatform(a.0,)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_GetHashCode_r_m<> for OSPlatform {
    fn GetHashCode(&self, ) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__GetHashCode__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_i32_GetHashCode_0_m<> for OSPlatform {
    fn GetHashCode_0(&self, ) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__GetHashCode__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_i32_GetHashCode_t_m<()> for OSPlatform {
    fn GetHashCode(&self, _a : ()) -> Result<i32,::System_Runtime::System::Exception> {
        self.i32__GetHashCode__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_op_Equality_r_f<&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform> for OSPlatform {
    fn op_Equality(p1 : &crate::System::Runtime::InteropServices::OSPlatform,p2 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__op_Equality__2__OSPlatform_OSPlatform(p1,p2)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_op_Equality_2_f<&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform> for OSPlatform {
    fn op_Equality_2(p1 : &crate::System::Runtime::InteropServices::OSPlatform,p2 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__op_Equality__2__OSPlatform_OSPlatform(p1,p2)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_op_Equality_t_f<(&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform)> for OSPlatform {
    fn op_Equality(a : (&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform)) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__op_Equality__2__OSPlatform_OSPlatform(a.0,a.1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_op_Inequality_r_f<&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform> for OSPlatform {
    fn op_Inequality(p1 : &crate::System::Runtime::InteropServices::OSPlatform,p2 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__op_Inequality__2__OSPlatform_OSPlatform(p1,p2)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_op_Inequality_2_f<&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform> for OSPlatform {
    fn op_Inequality_2(p1 : &crate::System::Runtime::InteropServices::OSPlatform,p2 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__op_Inequality__2__OSPlatform_OSPlatform(p1,p2)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_bool_op_Inequality_t_f<(&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform)> for OSPlatform {
    fn op_Inequality(a : (&crate::System::Runtime::InteropServices::OSPlatform,&crate::System::Runtime::InteropServices::OSPlatform)) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__op_Inequality__2__OSPlatform_OSPlatform(a.0,a.1)
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_ToString_r_m<> for OSPlatform {
    fn ToString(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__ToString__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_String_ToString_0_m<> for OSPlatform {
    fn ToString_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__ToString__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_String_ToString_t_m<()> for OSPlatform {
    fn ToString(&self, _a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__ToString__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_FreeBSD_s_f<> for OSPlatform {
    fn FreeBSD() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_FreeBSD__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_Linux_s_f<> for OSPlatform {
    fn Linux() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Linux__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_OSX_s_f<> for OSPlatform {
    fn OSX() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_OSX__0()
    }
}
impl System_Runtime_InteropServices_OSPlatform_overload_Windows_s_f<> for OSPlatform {
    fn Windows() -> Result<crate::System::Runtime::InteropServices::OSPlatform,::System_Runtime::System::Exception> {
        Self::OSPlatform__get_Windows__0()
    }
}

// System.Runtime.InteropServices.RuntimeInformation
// from System.Runtime.InteropServices.RuntimeInformation
pub struct RuntimeInformation;
impl RuntimeInformation {

    // [IsSpecialName] System.String get_FrameworkDescription()
    pub fn String__get_FrameworkDescription__0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_RuntimeInformation_String__get_FrameworkDescription__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_RuntimeInformation_String__get_FrameworkDescription__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Runtime.InteropServices.Architecture get_OSArchitecture()
    pub fn Architecture__get_OSArchitecture__0() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_RuntimeInformation_Architecture__get_OSArchitecture__0(thrown : *mut i64) -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_RuntimeInformation_Architecture__get_OSArchitecture__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.String get_OSDescription()
    pub fn String__get_OSDescription__0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_RuntimeInformation_String__get_OSDescription__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_RuntimeInformation_String__get_OSDescription__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Runtime.InteropServices.Architecture get_ProcessArchitecture()
    pub fn Architecture__get_ProcessArchitecture__0() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_RuntimeInformation_Architecture__get_ProcessArchitecture__0(thrown : *mut i64) -> i32;
        }
        unsafe {
            let __return = crate::System::Runtime::InteropServices::Architecture::from_value(System_Runtime_InteropServices_RuntimeInformation_Architecture__get_ProcessArchitecture__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.String get_RuntimeIdentifier()
    pub fn String__get_RuntimeIdentifier__0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_RuntimeInformation_String__get_RuntimeIdentifier__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Runtime_InteropServices_RuntimeInformation_String__get_RuntimeIdentifier__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Boolean IsOSPlatform(System.Runtime.InteropServices.OSPlatform)
    pub fn bool__IsOSPlatform__1__OSPlatform(_osPlatform : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Runtime_InteropServices_RuntimeInformation_bool__IsOSPlatform__1__OSPlatform(thrown : *mut i64, _osPlatform : i64) -> i32;
        }
        unsafe {
            let __return = (System_Runtime_InteropServices_RuntimeInformation_bool__IsOSPlatform__1__OSPlatform(&mut __thrown, _osPlatform.get_handle())) != 0;
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

pub trait System_Runtime_InteropServices_RuntimeInformation_overload_String_get_FrameworkDescription_t_f<TA> {
    fn get_FrameworkDescription(args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_get_FrameworkDescription_r_f<> {
    fn get_FrameworkDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_String_get_FrameworkDescription_0_f<> {
    fn get_FrameworkDescription_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_OSArchitecture_t_f<TA> {
    fn get_OSArchitecture(args : TA) -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_get_OSArchitecture_r_f<> {
    fn get_OSArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_OSArchitecture_0_f<> {
    fn get_OSArchitecture_0() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_String_get_OSDescription_t_f<TA> {
    fn get_OSDescription(args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_get_OSDescription_r_f<> {
    fn get_OSDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_String_get_OSDescription_0_f<> {
    fn get_OSDescription_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_ProcessArchitecture_t_f<TA> {
    fn get_ProcessArchitecture(args : TA) -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_get_ProcessArchitecture_r_f<> {
    fn get_ProcessArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_ProcessArchitecture_0_f<> {
    fn get_ProcessArchitecture_0() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_String_get_RuntimeIdentifier_t_f<TA> {
    fn get_RuntimeIdentifier(args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_get_RuntimeIdentifier_r_f<> {
    fn get_RuntimeIdentifier() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_String_get_RuntimeIdentifier_0_f<> {
    fn get_RuntimeIdentifier_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_bool_IsOSPlatform_t_f<TA> {
    fn IsOSPlatform(args : TA) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_IsOSPlatform_r_f<TA1> {
    fn IsOSPlatform(p1 : TA1) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_bool_IsOSPlatform_1_f<TA1> {
    fn IsOSPlatform_1(p1 : TA1) -> Result<bool,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_FrameworkDescription_s_f<> {
    fn FrameworkDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_OSArchitecture_s_f<> {
    fn OSArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_OSDescription_s_f<> {
    fn OSDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_ProcessArchitecture_s_f<> {
    fn ProcessArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception>;
}
pub trait System_Runtime_InteropServices_RuntimeInformation_overload_RuntimeIdentifier_s_f<> {
    fn RuntimeIdentifier() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_get_FrameworkDescription_r_f<> for RuntimeInformation {
    fn get_FrameworkDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_FrameworkDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_String_get_FrameworkDescription_0_f<> for RuntimeInformation {
    fn get_FrameworkDescription_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_FrameworkDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_String_get_FrameworkDescription_t_f<()> for RuntimeInformation {
    fn get_FrameworkDescription(_a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_FrameworkDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_get_OSArchitecture_r_f<> for RuntimeInformation {
    fn get_OSArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_OSArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_OSArchitecture_0_f<> for RuntimeInformation {
    fn get_OSArchitecture_0() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_OSArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_OSArchitecture_t_f<()> for RuntimeInformation {
    fn get_OSArchitecture(_a : ()) -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_OSArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_get_OSDescription_r_f<> for RuntimeInformation {
    fn get_OSDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_OSDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_String_get_OSDescription_0_f<> for RuntimeInformation {
    fn get_OSDescription_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_OSDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_String_get_OSDescription_t_f<()> for RuntimeInformation {
    fn get_OSDescription(_a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_OSDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_get_ProcessArchitecture_r_f<> for RuntimeInformation {
    fn get_ProcessArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_ProcessArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_ProcessArchitecture_0_f<> for RuntimeInformation {
    fn get_ProcessArchitecture_0() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_ProcessArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_ProcessArchitecture_t_f<()> for RuntimeInformation {
    fn get_ProcessArchitecture(_a : ()) -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_ProcessArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_get_RuntimeIdentifier_r_f<> for RuntimeInformation {
    fn get_RuntimeIdentifier() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_RuntimeIdentifier__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_String_get_RuntimeIdentifier_0_f<> for RuntimeInformation {
    fn get_RuntimeIdentifier_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_RuntimeIdentifier__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_String_get_RuntimeIdentifier_t_f<()> for RuntimeInformation {
    fn get_RuntimeIdentifier(_a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_RuntimeIdentifier__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_IsOSPlatform_r_f<&crate::System::Runtime::InteropServices::OSPlatform> for RuntimeInformation {
    fn IsOSPlatform(p1 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__IsOSPlatform__1__OSPlatform(p1)
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_bool_IsOSPlatform_1_f<&crate::System::Runtime::InteropServices::OSPlatform> for RuntimeInformation {
    fn IsOSPlatform_1(p1 : &crate::System::Runtime::InteropServices::OSPlatform) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__IsOSPlatform__1__OSPlatform(p1)
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_bool_IsOSPlatform_t_f<(&crate::System::Runtime::InteropServices::OSPlatform,)> for RuntimeInformation {
    fn IsOSPlatform(a : (&crate::System::Runtime::InteropServices::OSPlatform,)) -> Result<bool,::System_Runtime::System::Exception> {
        Self::bool__IsOSPlatform__1__OSPlatform(a.0,)
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_FrameworkDescription_s_f<> for RuntimeInformation {
    fn FrameworkDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_FrameworkDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_OSArchitecture_s_f<> for RuntimeInformation {
    fn OSArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_OSArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_OSDescription_s_f<> for RuntimeInformation {
    fn OSDescription() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_OSDescription__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_ProcessArchitecture_s_f<> for RuntimeInformation {
    fn ProcessArchitecture() -> Result<crate::System::Runtime::InteropServices::Architecture,::System_Runtime::System::Exception> {
        Self::Architecture__get_ProcessArchitecture__0()
    }
}
impl System_Runtime_InteropServices_RuntimeInformation_overload_RuntimeIdentifier_s_f<> for RuntimeInformation {
    fn RuntimeIdentifier() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__get_RuntimeIdentifier__0()
    }
}

} // System.Runtime.InteropServices

} // System.Runtime

} // System

pub mod overloads_with_count {
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_FreeBSD_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Linux_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_OSX_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Windows_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_Create_1_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_1_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_i32_GetHashCode_0_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_bool_op_Equality_2_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_bool_op_Inequality_2_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_String_ToString_0_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_String_get_FrameworkDescription_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_OSArchitecture_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_String_get_OSDescription_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_ProcessArchitecture_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_String_get_RuntimeIdentifier_0_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_bool_IsOSPlatform_1_f;
}
pub mod overloads_with_tuple {
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_FreeBSD_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Linux_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_OSX_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_get_Windows_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSPlatform_Create_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_bool_Equals_t_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_i32_GetHashCode_t_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_bool_op_Equality_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_bool_op_Inequality_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_String_ToString_t_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_String_get_FrameworkDescription_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_OSArchitecture_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_String_get_OSDescription_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_Architecture_get_ProcessArchitecture_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_String_get_RuntimeIdentifier_t_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_bool_IsOSPlatform_t_f;
}
pub mod overloads_special {
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_FreeBSD_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_Linux_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_OSX_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_Windows_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_FrameworkDescription_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_OSArchitecture_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_OSDescription_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_ProcessArchitecture_s_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_RuntimeIdentifier_s_f;
}
pub mod overloads_risky {
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_get_FreeBSD_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_get_Linux_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_get_OSX_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_get_Windows_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_Create_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_Equals_r_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_GetHashCode_r_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_op_Equality_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_op_Inequality_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_OSPlatform_overload_ToString_r_m;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_get_FrameworkDescription_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_get_OSArchitecture_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_get_OSDescription_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_get_ProcessArchitecture_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_get_RuntimeIdentifier_r_f;
pub use crate::System::Runtime::InteropServices::System_Runtime_InteropServices_RuntimeInformation_overload_IsOSPlatform_r_f;
}

