namespace Rustlyn.Backend;

/// <summary>
/// Generates NuGet package (.nupkg) from a translated Rust crate assembly.
/// Packages the translated .dll + .pdb + runtime dependencies into a NuGet package
/// ready for consumption by .NET projects.
/// </summary>
public static class NuGetPackager
{
    /// <summary>
    /// Creates a NuGet package specification for a translated crate.
    /// </summary>
    public static NuGetPackSpec CreatePackSpec(string crateName, string version, string outputAssemblyPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(crateName);
        ArgumentException.ThrowIfNullOrWhiteSpace(version);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputAssemblyPath);

        var packageId = $"Rustlyn.Crate.{ToPascalCase(crateName)}";
        var assemblyDir = Path.GetDirectoryName(Path.GetFullPath(outputAssemblyPath))
            ?? throw new InvalidOperationException("Cannot determine assembly directory.");

        var files = new List<NuGetPackFile>();

        // Main translated assembly
        files.Add(new NuGetPackFile(outputAssemblyPath, $"lib/net10.0/{Path.GetFileName(outputAssemblyPath)}"));

        // PDB if it exists
        var pdbPath = Path.ChangeExtension(outputAssemblyPath, ".pdb");
        if (File.Exists(pdbPath))
        {
            files.Add(new NuGetPackFile(pdbPath, $"lib/net10.0/{Path.GetFileName(pdbPath)}"));
        }

        // Runtime config
        var runtimeConfigPath = Path.ChangeExtension(outputAssemblyPath, ".runtimeconfig.json");
        if (File.Exists(runtimeConfigPath))
        {
            files.Add(new NuGetPackFile(runtimeConfigPath, $"lib/net10.0/{Path.GetFileName(runtimeConfigPath)}"));
        }

        // Collect runtime support assemblies in same directory
        foreach (var supportDll in Directory.EnumerateFiles(assemblyDir, "Rustlyn.*.dll"))
        {
            if (string.Equals(supportDll, Path.GetFullPath(outputAssemblyPath), StringComparison.OrdinalIgnoreCase))
                continue;
            files.Add(new NuGetPackFile(supportDll, $"lib/net10.0/{Path.GetFileName(supportDll)}"));
        }

        return new NuGetPackSpec(
            PackageId: packageId,
            Version: version,
            Description: $"Translated Rust crate '{crateName}' for .NET — generated by Rustlyn.",
            Authors: "Rustlyn",
            Tags: ["rust", "interop", "rustlyn", crateName],
            Files: files,
            Dependencies:
            [
                new NuGetPackDependency("Microsoft.NETCore.App.Ref", "10.0.0")
            ]);
    }

    /// <summary>
    /// Generates .nuspec XML content from a pack specification.
    /// </summary>
    public static string GenerateNuspec(NuGetPackSpec spec)
    {
        var filesXml = string.Join(Environment.NewLine,
            spec.Files.Select(f => $"      <file src=\"{EscapeXml(f.SourcePath)}\" target=\"{EscapeXml(f.TargetPath)}\" />"));

        var depsXml = string.Join(Environment.NewLine,
            spec.Dependencies.Select(d => $"        <dependency id=\"{EscapeXml(d.PackageId)}\" version=\"{EscapeXml(d.Version)}\" />"));

        return $"""
            <?xml version="1.0" encoding="utf-8"?>
            <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
              <metadata>
                <id>{EscapeXml(spec.PackageId)}</id>
                <version>{EscapeXml(spec.Version)}</version>
                <description>{EscapeXml(spec.Description)}</description>
                <authors>{EscapeXml(spec.Authors)}</authors>
                <tags>{EscapeXml(string.Join(" ", spec.Tags))}</tags>
                <dependencies>
                  <group targetFramework="net10.0">
            {depsXml}
                  </group>
                </dependencies>
              </metadata>
              <files>
            {filesXml}
              </files>
            </package>
            """;
    }

    private static string ToPascalCase(string snakeCase)
    {
        var parts = snakeCase.Split(['-', '_'], StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p =>
            p.Length == 0 ? "" : char.ToUpperInvariant(p[0]) + p[1..]));
    }

    private static string EscapeXml(string value)
    {
        return value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal)
            .Replace("\"", "&quot;", StringComparison.Ordinal);
    }

    /// <summary>
    /// Writes a real <c>.nupkg</c> (zip archive) to <paramref name="outputNupkgPath"/> containing
    /// the .nuspec, every file from <paramref name="spec"/>, and the standard NuGet
    /// <c>[Content_Types].xml</c> + <c>_rels/.rels</c> entries that make the package valid for
    /// <c>nuget restore</c> and IDE consumption.
    /// </summary>
    public static void WriteNupkg(NuGetPackSpec spec, string outputNupkgPath)
    {
        ArgumentNullException.ThrowIfNull(spec);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputNupkgPath);

        var dir = Path.GetDirectoryName(Path.GetFullPath(outputNupkgPath));
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }
        if (File.Exists(outputNupkgPath))
        {
            File.Delete(outputNupkgPath);
        }

        using var fs = File.Create(outputNupkgPath);
        using var zip = new System.IO.Compression.ZipArchive(fs, System.IO.Compression.ZipArchiveMode.Create);

        // 1. .nuspec at the root
        var nuspecName = $"{spec.PackageId}.nuspec";
        WriteZipText(zip, nuspecName, GenerateNuspec(spec));

        // 2. All declared files at their target paths
        foreach (var file in spec.Files)
        {
            if (!File.Exists(file.SourcePath))
            {
                continue;
            }
            var entry = zip.CreateEntry(NormalizeZipPath(file.TargetPath), System.IO.Compression.CompressionLevel.Optimal);
            using var entryStream = entry.Open();
            using var source = File.OpenRead(file.SourcePath);
            source.CopyTo(entryStream);
        }

        // 3. [Content_Types].xml — NuGet/OPC requirement
        WriteZipText(zip, "[Content_Types].xml", BuildContentTypesXml());

        // 4. _rels/.rels relating the package root to the nuspec
        WriteZipText(zip, "_rels/.rels", BuildRelsXml(nuspecName));
    }

    private static void WriteZipText(System.IO.Compression.ZipArchive zip, string path, string content)
    {
        var entry = zip.CreateEntry(NormalizeZipPath(path), System.IO.Compression.CompressionLevel.Optimal);
        using var stream = entry.Open();
        using var writer = new StreamWriter(stream, new System.Text.UTF8Encoding(false));
        writer.Write(content);
    }

    private static string NormalizeZipPath(string path) => path.Replace('\\', '/');

    private static string BuildContentTypesXml() => """
        <?xml version="1.0" encoding="utf-8"?>
        <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
          <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
          <Default Extension="nuspec" ContentType="application/octet" />
          <Default Extension="dll" ContentType="application/octet" />
          <Default Extension="pdb" ContentType="application/octet" />
          <Default Extension="json" ContentType="application/octet" />
          <Default Extension="xml" ContentType="application/octet" />
          <Default Extension="md" ContentType="application/octet" />
        </Types>
        """;

    private static string BuildRelsXml(string nuspecName) => $"""
        <?xml version="1.0" encoding="utf-8"?>
        <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
          <Relationship Type="http://schemas.microsoft.com/packaging/2010/07/manifest" Target="/{nuspecName}" Id="R1" />
        </Relationships>
        """;
}

/// <summary>
/// Specification for a NuGet package to be generated.
/// </summary>
public sealed record NuGetPackSpec(
    string PackageId,
    string Version,
    string Description,
    string Authors,
    IReadOnlyList<string> Tags,
    IReadOnlyList<NuGetPackFile> Files,
    IReadOnlyList<NuGetPackDependency> Dependencies);

/// <summary>
/// A file to include in the NuGet package.
/// </summary>
public sealed record NuGetPackFile(string SourcePath, string TargetPath);

/// <summary>
/// A NuGet package dependency.
/// </summary>
public sealed record NuGetPackDependency(string PackageId, string Version);
