using System.Text;

namespace RustMcil.Bindings;

public static class ManagedGlueGenerator
{
    public static string GenerateRuntimeBridgePartial(BindingSurface surface)
    {
        ArgumentNullException.ThrowIfNull(surface);

        foreach (var requirement in surface.Requirements)
        {
            requirement.Validate();
        }

        var builder = new StringBuilder();
        builder.AppendLine("// @generated by RustMcil.Bindings. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.IO;");
        builder.AppendLine("using RustMcil.Interop;");
        builder.AppendLine();
        builder.AppendLine("namespace RustMcil.Backend;");
        builder.AppendLine();
        builder.AppendLine("public static partial class RuntimeBridgeHelpers");
        builder.AppendLine("{");

        foreach (var binding in surface.ManagedGlueBindings)
        {
            binding.Validate();
            AppendMethod(builder, binding);
        }

        builder.AppendLine();
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendMethod(StringBuilder builder, ManagedGlueBinding binding)
    {
        builder.Append("    public static ");
        builder.Append(binding.ReturnType);
        builder.Append(' ');
        builder.Append(binding.RuntimeBridgeHelperMethodName);
        builder.Append('(');
        builder.AppendJoin(", ", binding.Parameters.Select(static parameter => $"{parameter.TypeName} {parameter.Name}"));
        builder.AppendLine(")");
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");

        if (binding.Operation.ExceptionConvention == ManagedGlueExceptionConvention.WriteExceptionOut)
        {
            builder.Append("            WriteExceptionOut(");
            builder.Append(binding.Operation.ExceptionOutParameterName);
            builder.AppendLine(", 0);");
        }

        AppendSuccessResult(builder, binding.Operation.Result);

        builder.AppendLine("        }");
        builder.AppendLine("        catch (Exception ex)");
        builder.AppendLine("        {");
        AppendCatchResult(builder, binding.Operation);
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendSuccessResult(StringBuilder builder, ManagedGlueResult result)
    {
        switch (result)
        {
            case ManagedGlueVoidCallResult voidCall:
                builder.Append("            ");
                builder.Append(voidCall.CallExpression.ToCode());
                builder.AppendLine(";");
                builder.AppendLine("            return 0;");
                break;

            case ManagedGlueObjectHandleResult objectHandle:
                builder.Append("            return ManagedInteropRuntime.AddObjectHandle(");
                builder.Append(objectHandle.ValueExpression.ToCode());
                builder.AppendLine(");");
                break;

            case ManagedGlueIntResult integer:
                builder.Append("            return ");
                builder.Append(integer.ValueExpression.ToCode());
                builder.AppendLine(";");
                break;

            case ManagedGlueBooleanAsIntResult boolean:
                builder.Append("            return ");
                builder.Append(boolean.ValueExpression.ToCode());
                builder.AppendLine();
                builder.AppendLine("                ? 1");
                builder.AppendLine("                : 0;");
                break;

            case ManagedGlueReleaseObjectResult releaseObject:
                builder.Append("            ManagedInteropRuntime.ReleaseObject(");
                builder.Append(releaseObject.HandleExpression);
                builder.AppendLine(");");
                builder.AppendLine("            return 0;");
                break;

            case ManagedGlueReleaseExceptionResult releaseException:
                builder.Append("            ManagedInteropRuntime.ReleaseException(");
                builder.Append(releaseException.HandleExpression);
                builder.AppendLine(");");
                builder.AppendLine("            return 0;");
                break;

            default:
                throw new NotSupportedException($"Managed glue result '{result.GetType().Name}' is not supported.");
        }
    }

    private static void AppendCatchResult(StringBuilder builder, ManagedGlueOperation operation)
    {
        switch (operation.ExceptionConvention)
        {
            case ManagedGlueExceptionConvention.ReturnExceptionHandle:
                builder.AppendLine("            return ManagedInteropRuntime.AddExceptionHandle(ex);");
                break;

            case ManagedGlueExceptionConvention.WriteExceptionOut:
                builder.Append("            WriteExceptionOut(");
                builder.Append(operation.ExceptionOutParameterName);
                builder.AppendLine(", ManagedInteropRuntime.AddExceptionHandle(ex));");
                builder.AppendLine("            return 0;");
                break;

            default:
                throw new NotSupportedException($"Managed glue exception convention '{operation.ExceptionConvention}' is not supported.");
        }
    }
}
