using System.Text;

namespace RustMcil.Bindings;

public static class RustBindingGenerator
{
    public static string GenerateSystemModule(BindingSurface surface)
    {
        ArgumentNullException.ThrowIfNull(surface);

        foreach (var requirement in surface.Requirements)
        {
            requirement.Validate();
        }

        var builder = new StringBuilder();
        builder.AppendLine("// @generated by RustMcil.Bindings. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("unsafe extern \"C\" {");
        foreach (var binding in surface.Externs)
        {
            foreach (var signatureLine in binding.SignatureLines)
            {
                builder.Append("    ");
                builder.AppendLine(signatureLine);
            }
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.Append(GenerateRustWrapperBody(surface));
        return builder.ToString();
    }

    private static string GenerateRustWrapperBody(BindingSurface surface)
    {
        return RustWrapperBodyTemplate.Replace(
            "{{MATHF_METHODS}}",
            GenerateRustWrapperMethods(surface.RustWrapperMethods, RustWrapperContainer.MathF, "    "),
            StringComparison.Ordinal).Replace(
            "{{IO_PATH_METHODS}}",
            GenerateRustWrapperMethods(surface.RustWrapperMethods, RustWrapperContainer.IoPath, "        "),
            StringComparison.Ordinal);
    }

    private static string GenerateRustWrapperMethods(IReadOnlyList<RustWrapperMethod> methods, RustWrapperContainer container, string indent)
    {
        var builder = new StringBuilder();
        var selectedMethods = methods.Where(method => method.Container == container).ToArray();
        for (var index = 0; index < selectedMethods.Length; index++)
        {
            if (index > 0)
            {
                builder.AppendLine();
            }

            AppendRustWrapperMethod(builder, selectedMethods[index], indent);
        }

        return builder.ToString().TrimEnd('\r', '\n');
    }

    private static void AppendRustWrapperMethod(StringBuilder builder, RustWrapperMethod method, string indent)
    {
        builder.Append(indent);
        builder.Append(method.Signature);
        builder.AppendLine(" {");
        builder.Append(indent);
        builder.AppendLine("    let mut exception_handle = 0;");
        builder.Append(indent);
        builder.Append("    let ");
        builder.Append(method.ResultVariableName);
        builder.AppendLine(" = unsafe {");
        builder.Append(indent);
        builder.Append("        ");
        builder.Append(GetRustWrapperSymbolAccess(method));
        builder.AppendLine("(");
        foreach (var argument in method.Arguments)
        {
            builder.Append(indent);
            builder.Append("            ");
            builder.Append(argument);
            builder.AppendLine(",");
        }

        builder.Append(indent);
        builder.AppendLine("            &mut exception_handle,");
        builder.Append(indent);
        builder.AppendLine("        )");
        builder.Append(indent);
        builder.AppendLine("    };");
        builder.Append(indent);
        builder.AppendLine("    Exception::from_handle(exception_handle)?;");
        builder.Append(indent);
        builder.Append("    ");
        builder.AppendLine(FormatRustWrapperSuccess(method));
        builder.Append(indent);
        builder.AppendLine("}");
    }

    private static string GetRustWrapperSymbolAccess(RustWrapperMethod method)
    {
        return method.Container switch
        {
            RustWrapperContainer.MathF => $"super::{method.ExternSymbol}",
            RustWrapperContainer.IoPath => $"super::super::{method.ExternSymbol}",
            _ => throw new NotSupportedException($"Rust wrapper container '{method.Container}' is not supported.")
        };
    }

    private static string FormatRustWrapperSuccess(RustWrapperMethod method)
    {
        return method.Result.Kind switch
        {
            RustWrapperResultKind.BooleanAsInt => $"Ok({method.ResultVariableName})",
            RustWrapperResultKind.ObjectHandle => $"Ok({method.Result.RustType}::from_handle({method.ResultVariableName}))",
            RustWrapperResultKind.Scalar => $"Ok({method.ResultVariableName})",
            _ => throw new NotSupportedException($"Rust wrapper result kind '{method.Result.Kind}' is not supported.")
        };
    }

    private const string RustWrapperBodyTemplate = """
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Exception {
    handle: i32,
}

impl Exception {
    fn from_handle(handle: i32) -> Result<(), Self> {
        if handle == 0 {
            Ok(())
        } else {
            Err(Self { handle })
        }
    }
}

pub mod console {
    use crate::system::{Exception, ManagedString};

    pub fn write_line_utf8_parts(value_ptr: *const u8, value_len: i64) -> Result<(), Exception> {
        let exception_handle = unsafe {
            super::rust_mcil_bindgen_system_console_write_line_utf8(
                value_ptr,
                value_len,
            )
        };

        Exception::from_handle(exception_handle)
    }

    pub fn write_line(value: &ManagedString) -> Result<(), Exception> {
        let exception_handle = unsafe { super::rust_mcil_bindgen_system_console_write_line_string(value.handle()) };
        Exception::from_handle(exception_handle)
    }
}

pub mod environment {
    use crate::system::{Exception, ManagedString, ManagedStringArray};

    pub fn current_directory() -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rust_mcil_bindgen_system_environment_current_directory(
                &mut exception_handle,
            )
        };

        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(object_handle))
    }

    pub fn get_command_line_args() -> Result<ManagedStringArray, Exception> {
        let mut exception_handle = 0;
        let object_handle = unsafe {
            super::rust_mcil_bindgen_system_environment_get_command_line_args(
                &mut exception_handle,
            )
        };

        Exception::from_handle(exception_handle)?;
        Ok(ManagedStringArray::from_handle(object_handle))
    }
}

pub mod mathf {
    use crate::system::Exception;

{{MATHF_METHODS}}
}

pub mod io {
    pub mod directory {
        use crate::system::{Exception, ManagedString};

        pub fn get_current_directory() -> Result<ManagedString, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rust_mcil_bindgen_system_io_directory_get_current_directory(
                    &mut exception_handle,
                )
            };

            Exception::from_handle(exception_handle)?;
            Ok(ManagedString::from_handle(object_handle))
        }
    }

    pub mod file {
        use crate::system::{Exception, ManagedString, ManagedStringArray};

        pub fn read_all_lines_utf8_parts(path_ptr: *const u8, path_len: i64) -> Result<ManagedStringArray, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rust_mcil_bindgen_system_io_file_read_all_lines_utf8(
                    path_ptr,
                    path_len,
                    &mut exception_handle,
                )
            };

            Exception::from_handle(exception_handle)?;
            Ok(ManagedStringArray::from_handle(object_handle))
        }

        pub fn read_all_lines(path: &ManagedString) -> Result<ManagedStringArray, Exception> {
            let mut exception_handle = 0;
            let object_handle = unsafe {
                super::super::rust_mcil_bindgen_system_io_file_read_all_lines_string(
                    path.handle(),
                    &mut exception_handle,
                )
            };

            Exception::from_handle(exception_handle)?;
            Ok(ManagedStringArray::from_handle(object_handle))
        }
    }

    pub mod path {
        use crate::system::{Exception, ManagedString};

{{IO_PATH_METHODS}}
    }
}

pub struct ManagedString {
    handle: i32,
}

impl ManagedString {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn from_utf8_parts(value_ptr: *const u8, value_len: i64) -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let string_handle = unsafe {
            rust_mcil_bindgen_system_string_from_utf8(
                value_ptr,
                value_len,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(Self::from_handle(string_handle))
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rust_mcil_bindgen_system_string_len(self.handle, &mut exception_handle)
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn utf8_len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rust_mcil_bindgen_system_string_utf8_len(self.handle, &mut exception_handle)
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn copy_utf8_into(&self, buffer: &mut [u8]) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let written = unsafe {
            rust_mcil_bindgen_system_string_copy_utf8(
                self.handle,
                buffer.as_mut_ptr(),
                buffer.len() as i64,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(written)
    }

    pub fn contains_utf8_parts(&self, needle_ptr: *const u8, needle_len: i64) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let contains = unsafe {
            rust_mcil_bindgen_system_string_contains_utf8(
                self.handle,
                needle_ptr,
                needle_len,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(contains != 0)
    }

    pub fn contains(&self, needle: &ManagedString) -> Result<bool, Exception> {
        let mut exception_handle = 0;
        let contains = unsafe {
            rust_mcil_bindgen_system_string_contains_string(
                self.handle,
                needle.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(contains != 0)
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe { rust_mcil_bindgen_system_object_release(self.handle) };
        Exception::from_handle(exception_handle)
    }
}

pub struct ManagedStringArray {
    handle: i32,
}

impl ManagedStringArray {
    fn from_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn len(&self) -> Result<i32, Exception> {
        let mut exception_handle = 0;
        let length = unsafe {
            rust_mcil_bindgen_system_string_array_len(self.handle, &mut exception_handle)
        };
        Exception::from_handle(exception_handle)?;
        Ok(length)
    }

    pub fn get(&self, index: i32) -> Result<ManagedString, Exception> {
        let mut exception_handle = 0;
        let string_handle = unsafe {
            rust_mcil_bindgen_system_string_array_get(self.handle, index, &mut exception_handle)
        };
        Exception::from_handle(exception_handle)?;
        Ok(ManagedString::from_handle(string_handle))
    }

    pub fn release(self) -> Result<(), Exception> {
        let exception_handle = unsafe { rust_mcil_bindgen_system_object_release(self.handle) };
        Exception::from_handle(exception_handle)
    }
}
""";
}
