// this file is automatically generated
// Copyright 2020 SourceGear
#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_unsafe)]
#![allow(unused_imports)]
#![allow(unused_parens)]

extern {
    fn __drop_handle(self_h : i64);
    fn __copy_handle(self_h : i64) -> i64;
}

// System
pub mod System {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Net
pub mod Net {
    use sgrust_core::SGRustObjectHandle;
    use sgrust_core::SGRustValue;

// System.Net.Dns
// from System.Net.NameResolution
pub struct Dns;
impl Dns {

    // System.IAsyncResult BeginGetHostAddresses(System.String, System.AsyncCallback, System.Object)
    pub fn IAsyncResult__BeginGetHostAddresses__3__String_AsyncCallback_Object(_hostNameOrAddress : &::System_Runtime::System::String, _requestCallback : &::System_Runtime::System::AsyncCallback, _state : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IAsyncResult__BeginGetHostAddresses__3__String_AsyncCallback_Object(thrown : *mut i64, _hostNameOrAddress : i64, _requestCallback : i64, _state : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IAsyncResult__BeginGetHostAddresses__3__String_AsyncCallback_Object(&mut __thrown, _hostNameOrAddress.get_handle(), _requestCallback.get_handle(), _state.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.IAsyncResult BeginGetHostByName(System.String, System.AsyncCallback, System.Object)
    pub fn IAsyncResult__BeginGetHostByName__3__String_AsyncCallback_Object(_hostName : &::System_Runtime::System::String, _requestCallback : &::System_Runtime::System::AsyncCallback, _stateObject : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IAsyncResult__BeginGetHostByName__3__String_AsyncCallback_Object(thrown : *mut i64, _hostName : i64, _requestCallback : i64, _stateObject : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IAsyncResult__BeginGetHostByName__3__String_AsyncCallback_Object(&mut __thrown, _hostName.get_handle(), _requestCallback.get_handle(), _stateObject.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.IAsyncResult BeginGetHostEntry(System.Net.IPAddress, System.AsyncCallback, System.Object)
    pub fn IAsyncResult__BeginGetHostEntry__3__IPAddress_AsyncCallback_Object(_address : &::System_Net_Primitives::System::Net::IPAddress, _requestCallback : &::System_Runtime::System::AsyncCallback, _stateObject : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IAsyncResult__BeginGetHostEntry__3__IPAddress_AsyncCallback_Object(thrown : *mut i64, _address : i64, _requestCallback : i64, _stateObject : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IAsyncResult__BeginGetHostEntry__3__IPAddress_AsyncCallback_Object(&mut __thrown, _address.get_handle(), _requestCallback.get_handle(), _stateObject.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.IAsyncResult BeginGetHostEntry(System.String, System.AsyncCallback, System.Object)
    pub fn IAsyncResult__BeginGetHostEntry__3__String_AsyncCallback_Object(_hostNameOrAddress : &::System_Runtime::System::String, _requestCallback : &::System_Runtime::System::AsyncCallback, _stateObject : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IAsyncResult__BeginGetHostEntry__3__String_AsyncCallback_Object(thrown : *mut i64, _hostNameOrAddress : i64, _requestCallback : i64, _stateObject : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IAsyncResult__BeginGetHostEntry__3__String_AsyncCallback_Object(&mut __thrown, _hostNameOrAddress.get_handle(), _requestCallback.get_handle(), _stateObject.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.IAsyncResult BeginResolve(System.String, System.AsyncCallback, System.Object)
    pub fn IAsyncResult__BeginResolve__3__String_AsyncCallback_Object(_hostName : &::System_Runtime::System::String, _requestCallback : &::System_Runtime::System::AsyncCallback, _stateObject : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IAsyncResult__BeginResolve__3__String_AsyncCallback_Object(thrown : *mut i64, _hostName : i64, _requestCallback : i64, _stateObject : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IAsyncResult__BeginResolve__3__String_AsyncCallback_Object(&mut __thrown, _hostName.get_handle(), _requestCallback.get_handle(), _stateObject.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPAddress[] EndGetHostAddresses(System.IAsyncResult)
    pub fn IPAddressArray__EndGetHostAddresses__1__IAsyncResult(_asyncResult : &::System_Runtime::System::IAsyncResult) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPAddressArray__EndGetHostAddresses__1__IAsyncResult(thrown : *mut i64, _asyncResult : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPAddressArray__EndGetHostAddresses__1__IAsyncResult(&mut __thrown, _asyncResult.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry EndGetHostByName(System.IAsyncResult)
    pub fn IPHostEntry__EndGetHostByName__1__IAsyncResult(_asyncResult : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__EndGetHostByName__1__IAsyncResult(thrown : *mut i64, _asyncResult : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__EndGetHostByName__1__IAsyncResult(&mut __thrown, _asyncResult.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry EndGetHostEntry(System.IAsyncResult)
    pub fn IPHostEntry__EndGetHostEntry__1__IAsyncResult(_asyncResult : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__EndGetHostEntry__1__IAsyncResult(thrown : *mut i64, _asyncResult : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__EndGetHostEntry__1__IAsyncResult(&mut __thrown, _asyncResult.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry EndResolve(System.IAsyncResult)
    pub fn IPHostEntry__EndResolve__1__IAsyncResult(_asyncResult : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__EndResolve__1__IAsyncResult(thrown : *mut i64, _asyncResult : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__EndResolve__1__IAsyncResult(&mut __thrown, _asyncResult.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPAddress[] GetHostAddresses(System.String)
    pub fn IPAddressArray__GetHostAddresses__1__String(_hostNameOrAddress : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPAddressArray__GetHostAddresses__1__String(thrown : *mut i64, _hostNameOrAddress : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPAddressArray__GetHostAddresses__1__String(&mut __thrown, _hostNameOrAddress.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Threading.Tasks.Task<System.Net.IPAddress[]> GetHostAddressesAsync(System.String)
    pub fn System_Threading_Tasks_Task_System_Net_IPAddressArray___GetHostAddressesAsync__1__String(_hostNameOrAddress : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_System_Threading_Tasks_Task_System_Net_IPAddressArray___GetHostAddressesAsync__1__String(thrown : *mut i64, _hostNameOrAddress : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_System_Threading_Tasks_Task_System_Net_IPAddressArray___GetHostAddressesAsync__1__String(&mut __thrown, _hostNameOrAddress.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry GetHostByAddress(System.Net.IPAddress)
    pub fn IPHostEntry__GetHostByAddress__1__IPAddress(_address : &::System_Net_Primitives::System::Net::IPAddress) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__GetHostByAddress__1__IPAddress(thrown : *mut i64, _address : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__GetHostByAddress__1__IPAddress(&mut __thrown, _address.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry GetHostByAddress(System.String)
    pub fn IPHostEntry__GetHostByAddress__1__String(_address : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__GetHostByAddress__1__String(thrown : *mut i64, _address : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__GetHostByAddress__1__String(&mut __thrown, _address.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry GetHostByName(System.String)
    pub fn IPHostEntry__GetHostByName__1__String(_hostName : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__GetHostByName__1__String(thrown : *mut i64, _hostName : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__GetHostByName__1__String(&mut __thrown, _hostName.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry GetHostEntry(System.Net.IPAddress)
    pub fn IPHostEntry__GetHostEntry__1__IPAddress(_address : &::System_Net_Primitives::System::Net::IPAddress) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__GetHostEntry__1__IPAddress(thrown : *mut i64, _address : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__GetHostEntry__1__IPAddress(&mut __thrown, _address.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry GetHostEntry(System.String)
    pub fn IPHostEntry__GetHostEntry__1__String(_hostNameOrAddress : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__GetHostEntry__1__String(thrown : *mut i64, _hostNameOrAddress : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__GetHostEntry__1__String(&mut __thrown, _hostNameOrAddress.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Threading.Tasks.Task<System.Net.IPHostEntry> GetHostEntryAsync(System.Net.IPAddress)
    pub fn System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__IPAddress(_address : &::System_Net_Primitives::System::Net::IPAddress) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__IPAddress(thrown : *mut i64, _address : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__IPAddress(&mut __thrown, _address.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Threading.Tasks.Task<System.Net.IPHostEntry> GetHostEntryAsync(System.String)
    pub fn System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__String(_hostNameOrAddress : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__String(thrown : *mut i64, _hostNameOrAddress : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__String(&mut __thrown, _hostNameOrAddress.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.String GetHostName()
    pub fn String__GetHostName__0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_String__GetHostName__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_String__GetHostName__0(&mut __thrown));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // System.Net.IPHostEntry Resolve(System.String)
    pub fn IPHostEntry__Resolve__1__String(_hostName : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_Dns_IPHostEntry__Resolve__1__String(thrown : *mut i64, _hostName : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_Dns_IPHostEntry__Resolve__1__String(&mut __thrown, _hostName.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

pub trait System_Net_Dns_overload_IAsyncResult_BeginGetHostAddresses_t_f<TA> {
    fn BeginGetHostAddresses(args : TA) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_BeginGetHostAddresses_r_f<TA1,TA2,TA3> {
    fn BeginGetHostAddresses(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginGetHostAddresses_3_f<TA1,TA2,TA3> {
    fn BeginGetHostAddresses_3(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginGetHostByName_t_f<TA> {
    fn BeginGetHostByName(args : TA) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_BeginGetHostByName_r_f<TA1,TA2,TA3> {
    fn BeginGetHostByName(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginGetHostByName_3_f<TA1,TA2,TA3> {
    fn BeginGetHostByName_3(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_t_f<TA> {
    fn BeginGetHostEntry(args : TA) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_BeginGetHostEntry_r_f<TA1,TA2,TA3> {
    fn BeginGetHostEntry(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_3_f<TA1,TA2,TA3> {
    fn BeginGetHostEntry_3(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginResolve_t_f<TA> {
    fn BeginResolve(args : TA) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_BeginResolve_r_f<TA1,TA2,TA3> {
    fn BeginResolve(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IAsyncResult_BeginResolve_3_f<TA1,TA2,TA3> {
    fn BeginResolve_3(p1 : TA1,p2 : TA2,p3 : TA3) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPAddressArray_EndGetHostAddresses_t_f<TA> {
    fn EndGetHostAddresses(args : TA) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_EndGetHostAddresses_r_f<TA1> {
    fn EndGetHostAddresses(p1 : TA1) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPAddressArray_EndGetHostAddresses_1_f<TA1> {
    fn EndGetHostAddresses_1(p1 : TA1) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_EndGetHostByName_t_f<TA> {
    fn EndGetHostByName(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_EndGetHostByName_r_f<TA1> {
    fn EndGetHostByName(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_EndGetHostByName_1_f<TA1> {
    fn EndGetHostByName_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_EndGetHostEntry_t_f<TA> {
    fn EndGetHostEntry(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_EndGetHostEntry_r_f<TA1> {
    fn EndGetHostEntry(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_EndGetHostEntry_1_f<TA1> {
    fn EndGetHostEntry_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_EndResolve_t_f<TA> {
    fn EndResolve(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_EndResolve_r_f<TA1> {
    fn EndResolve(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_EndResolve_1_f<TA1> {
    fn EndResolve_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPAddressArray_GetHostAddresses_t_f<TA> {
    fn GetHostAddresses(args : TA) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostAddresses_r_f<TA1> {
    fn GetHostAddresses(p1 : TA1) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPAddressArray_GetHostAddresses_1_f<TA1> {
    fn GetHostAddresses_1(p1 : TA1) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPAddressArray__GetHostAddressesAsync_t_f<TA> {
    fn GetHostAddressesAsync(args : TA) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostAddressesAsync_r_f<TA1> {
    fn GetHostAddressesAsync(p1 : TA1) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPAddressArray__GetHostAddressesAsync_1_f<TA1> {
    fn GetHostAddressesAsync_1(p1 : TA1) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_GetHostByAddress_t_f<TA> {
    fn GetHostByAddress(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostByAddress_r_f<TA1> {
    fn GetHostByAddress(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_GetHostByAddress_1_f<TA1> {
    fn GetHostByAddress_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_GetHostByName_t_f<TA> {
    fn GetHostByName(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostByName_r_f<TA1> {
    fn GetHostByName(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_GetHostByName_1_f<TA1> {
    fn GetHostByName_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_GetHostEntry_t_f<TA> {
    fn GetHostEntry(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostEntry_r_f<TA1> {
    fn GetHostEntry(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_GetHostEntry_1_f<TA1> {
    fn GetHostEntry_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_t_f<TA> {
    fn GetHostEntryAsync(args : TA) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostEntryAsync_r_f<TA1> {
    fn GetHostEntryAsync(p1 : TA1) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_1_f<TA1> {
    fn GetHostEntryAsync_1(p1 : TA1) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_String_GetHostName_t_f<TA> {
    fn GetHostName(args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_GetHostName_r_f<> {
    fn GetHostName() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_String_GetHostName_0_f<> {
    fn GetHostName_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_Resolve_t_f<TA> {
    fn Resolve(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_Resolve_r_f<TA1> {
    fn Resolve(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_Dns_overload_IPHostEntry_Resolve_1_f<TA1> {
    fn Resolve_1(p1 : TA1) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
impl System_Net_Dns_overload_BeginGetHostAddresses_r_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostAddresses(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostAddresses__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostAddresses_3_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostAddresses_3(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostAddresses__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostAddresses_t_f<(&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)> for Dns {
    fn BeginGetHostAddresses(a : (&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostAddresses__3__String_AsyncCallback_Object(a.0,a.1,a.2)
    }
}
impl System_Net_Dns_overload_BeginGetHostByName_r_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostByName(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostByName__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostByName_3_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostByName_3(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostByName__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostByName_t_f<(&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)> for Dns {
    fn BeginGetHostByName(a : (&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostByName__3__String_AsyncCallback_Object(a.0,a.1,a.2)
    }
}
impl System_Net_Dns_overload_BeginGetHostEntry_r_f<&::System_Net_Primitives::System::Net::IPAddress,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostEntry(p1 : &::System_Net_Primitives::System::Net::IPAddress,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostEntry__3__IPAddress_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_3_f<&::System_Net_Primitives::System::Net::IPAddress,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostEntry_3(p1 : &::System_Net_Primitives::System::Net::IPAddress,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostEntry__3__IPAddress_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_t_f<(&::System_Net_Primitives::System::Net::IPAddress,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)> for Dns {
    fn BeginGetHostEntry(a : (&::System_Net_Primitives::System::Net::IPAddress,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostEntry__3__IPAddress_AsyncCallback_Object(a.0,a.1,a.2)
    }
}
impl System_Net_Dns_overload_BeginGetHostEntry_r_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostEntry(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostEntry__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_3_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginGetHostEntry_3(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostEntry__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_t_f<(&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)> for Dns {
    fn BeginGetHostEntry(a : (&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginGetHostEntry__3__String_AsyncCallback_Object(a.0,a.1,a.2)
    }
}
impl System_Net_Dns_overload_BeginResolve_r_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginResolve(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginResolve__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginResolve_3_f<&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object> for Dns {
    fn BeginResolve_3(p1 : &::System_Runtime::System::String,p2 : &::System_Runtime::System::AsyncCallback,p3 : &::System_Runtime::System::Object) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginResolve__3__String_AsyncCallback_Object(p1,p2,p3)
    }
}
impl System_Net_Dns_overload_IAsyncResult_BeginResolve_t_f<(&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)> for Dns {
    fn BeginResolve(a : (&::System_Runtime::System::String,&::System_Runtime::System::AsyncCallback,&::System_Runtime::System::Object)) -> Result<::System_Runtime::System::IAsyncResult,::System_Runtime::System::Exception> {
        Self::IAsyncResult__BeginResolve__3__String_AsyncCallback_Object(a.0,a.1,a.2)
    }
}
impl System_Net_Dns_overload_EndGetHostAddresses_r_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndGetHostAddresses(p1 : &::System_Runtime::System::IAsyncResult) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        Self::IPAddressArray__EndGetHostAddresses__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPAddressArray_EndGetHostAddresses_1_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndGetHostAddresses_1(p1 : &::System_Runtime::System::IAsyncResult) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        Self::IPAddressArray__EndGetHostAddresses__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPAddressArray_EndGetHostAddresses_t_f<(&::System_Runtime::System::IAsyncResult,)> for Dns {
    fn EndGetHostAddresses(a : (&::System_Runtime::System::IAsyncResult,)) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        Self::IPAddressArray__EndGetHostAddresses__1__IAsyncResult(a.0,)
    }
}
impl System_Net_Dns_overload_EndGetHostByName_r_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndGetHostByName(p1 : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndGetHostByName__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_EndGetHostByName_1_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndGetHostByName_1(p1 : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndGetHostByName__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_EndGetHostByName_t_f<(&::System_Runtime::System::IAsyncResult,)> for Dns {
    fn EndGetHostByName(a : (&::System_Runtime::System::IAsyncResult,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndGetHostByName__1__IAsyncResult(a.0,)
    }
}
impl System_Net_Dns_overload_EndGetHostEntry_r_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndGetHostEntry(p1 : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndGetHostEntry__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_EndGetHostEntry_1_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndGetHostEntry_1(p1 : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndGetHostEntry__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_EndGetHostEntry_t_f<(&::System_Runtime::System::IAsyncResult,)> for Dns {
    fn EndGetHostEntry(a : (&::System_Runtime::System::IAsyncResult,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndGetHostEntry__1__IAsyncResult(a.0,)
    }
}
impl System_Net_Dns_overload_EndResolve_r_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndResolve(p1 : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndResolve__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_EndResolve_1_f<&::System_Runtime::System::IAsyncResult> for Dns {
    fn EndResolve_1(p1 : &::System_Runtime::System::IAsyncResult) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndResolve__1__IAsyncResult(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_EndResolve_t_f<(&::System_Runtime::System::IAsyncResult,)> for Dns {
    fn EndResolve(a : (&::System_Runtime::System::IAsyncResult,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__EndResolve__1__IAsyncResult(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostAddresses_r_f<&::System_Runtime::System::String> for Dns {
    fn GetHostAddresses(p1 : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        Self::IPAddressArray__GetHostAddresses__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPAddressArray_GetHostAddresses_1_f<&::System_Runtime::System::String> for Dns {
    fn GetHostAddresses_1(p1 : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        Self::IPAddressArray__GetHostAddresses__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPAddressArray_GetHostAddresses_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn GetHostAddresses(a : (&::System_Runtime::System::String,)) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        Self::IPAddressArray__GetHostAddresses__1__String(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostAddressesAsync_r_f<&::System_Runtime::System::String> for Dns {
    fn GetHostAddressesAsync(p1 : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPAddressArray___GetHostAddressesAsync__1__String(p1)
    }
}
impl System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPAddressArray__GetHostAddressesAsync_1_f<&::System_Runtime::System::String> for Dns {
    fn GetHostAddressesAsync_1(p1 : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPAddressArray___GetHostAddressesAsync__1__String(p1)
    }
}
impl System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPAddressArray__GetHostAddressesAsync_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn GetHostAddressesAsync(a : (&::System_Runtime::System::String,)) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPAddressArray___GetHostAddressesAsync__1__String(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostByAddress_r_f<&::System_Net_Primitives::System::Net::IPAddress> for Dns {
    fn GetHostByAddress(p1 : &::System_Net_Primitives::System::Net::IPAddress) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByAddress__1__IPAddress(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostByAddress_1_f<&::System_Net_Primitives::System::Net::IPAddress> for Dns {
    fn GetHostByAddress_1(p1 : &::System_Net_Primitives::System::Net::IPAddress) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByAddress__1__IPAddress(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostByAddress_t_f<(&::System_Net_Primitives::System::Net::IPAddress,)> for Dns {
    fn GetHostByAddress(a : (&::System_Net_Primitives::System::Net::IPAddress,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByAddress__1__IPAddress(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostByAddress_r_f<&::System_Runtime::System::String> for Dns {
    fn GetHostByAddress(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByAddress__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostByAddress_1_f<&::System_Runtime::System::String> for Dns {
    fn GetHostByAddress_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByAddress__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostByAddress_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn GetHostByAddress(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByAddress__1__String(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostByName_r_f<&::System_Runtime::System::String> for Dns {
    fn GetHostByName(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByName__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostByName_1_f<&::System_Runtime::System::String> for Dns {
    fn GetHostByName_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByName__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostByName_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn GetHostByName(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostByName__1__String(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostEntry_r_f<&::System_Net_Primitives::System::Net::IPAddress> for Dns {
    fn GetHostEntry(p1 : &::System_Net_Primitives::System::Net::IPAddress) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostEntry__1__IPAddress(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostEntry_1_f<&::System_Net_Primitives::System::Net::IPAddress> for Dns {
    fn GetHostEntry_1(p1 : &::System_Net_Primitives::System::Net::IPAddress) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostEntry__1__IPAddress(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostEntry_t_f<(&::System_Net_Primitives::System::Net::IPAddress,)> for Dns {
    fn GetHostEntry(a : (&::System_Net_Primitives::System::Net::IPAddress,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostEntry__1__IPAddress(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostEntry_r_f<&::System_Runtime::System::String> for Dns {
    fn GetHostEntry(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostEntry__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostEntry_1_f<&::System_Runtime::System::String> for Dns {
    fn GetHostEntry_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostEntry__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_GetHostEntry_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn GetHostEntry(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__GetHostEntry__1__String(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostEntryAsync_r_f<&::System_Net_Primitives::System::Net::IPAddress> for Dns {
    fn GetHostEntryAsync(p1 : &::System_Net_Primitives::System::Net::IPAddress) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__IPAddress(p1)
    }
}
impl System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_1_f<&::System_Net_Primitives::System::Net::IPAddress> for Dns {
    fn GetHostEntryAsync_1(p1 : &::System_Net_Primitives::System::Net::IPAddress) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__IPAddress(p1)
    }
}
impl System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_t_f<(&::System_Net_Primitives::System::Net::IPAddress,)> for Dns {
    fn GetHostEntryAsync(a : (&::System_Net_Primitives::System::Net::IPAddress,)) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__IPAddress(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostEntryAsync_r_f<&::System_Runtime::System::String> for Dns {
    fn GetHostEntryAsync(p1 : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__String(p1)
    }
}
impl System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_1_f<&::System_Runtime::System::String> for Dns {
    fn GetHostEntryAsync_1(p1 : &::System_Runtime::System::String) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__String(p1)
    }
}
impl System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn GetHostEntryAsync(a : (&::System_Runtime::System::String,)) -> Result<::System_Runtime::System::Threading::Tasks::Task_1<crate::System::Net::IPHostEntry>,::System_Runtime::System::Exception> {
        Self::System_Threading_Tasks_Task_System_Net_IPHostEntry___GetHostEntryAsync__1__String(a.0,)
    }
}
impl System_Net_Dns_overload_GetHostName_r_f<> for Dns {
    fn GetHostName() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__GetHostName__0()
    }
}
impl System_Net_Dns_overload_String_GetHostName_0_f<> for Dns {
    fn GetHostName_0() -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__GetHostName__0()
    }
}
impl System_Net_Dns_overload_String_GetHostName_t_f<()> for Dns {
    fn GetHostName(_a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        Self::String__GetHostName__0()
    }
}
impl System_Net_Dns_overload_Resolve_r_f<&::System_Runtime::System::String> for Dns {
    fn Resolve(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__Resolve__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_Resolve_1_f<&::System_Runtime::System::String> for Dns {
    fn Resolve_1(p1 : &::System_Runtime::System::String) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__Resolve__1__String(p1)
    }
}
impl System_Net_Dns_overload_IPHostEntry_Resolve_t_f<(&::System_Runtime::System::String,)> for Dns {
    fn Resolve(a : (&::System_Runtime::System::String,)) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::IPHostEntry__Resolve__1__String(a.0,)
    }
}

// System.Net.IPHostEntry
// from System.Net.NameResolution
#[derive(Debug)]
pub struct IPHostEntry {
    h : i64
}

impl ::sgrust_core::SGRustValue for IPHostEntry {
    fn get_type_handle() -> i64 {
        extern {
            fn System_Net_IPHostEntry_get_type_handle() -> i64;
        }
        unsafe {
            return System_Net_IPHostEntry_get_type_handle();
        }
    }
    fn to_ffi(&self) -> i64 { return self.h; }
    fn from_ffi(hndl : i64) -> Self { return Self { h : hndl } }
}

impl ::sgrust_core::SGRustObjectHandle for IPHostEntry {
    fn get_handle(&self) -> i64 { return self.h; }
    fn from_handle(hndl : i64) -> Self { return Self { h : hndl } }
}

impl IPHostEntry {

    // .ctor()
    pub fn ctor__0() -> Result<Self,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_ctor__0(thrown : *mut i64) -> i64;
        }
        unsafe {
            let h = System_Net_IPHostEntry_ctor__0(&mut __thrown);
            if __thrown == 0 {
                return Ok(Self::from_handle(h));
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Net.IPAddress[] get_AddressList()
    pub fn IPAddressArray__get_AddressList__0(&self) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_IPAddressArray__get_AddressList__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_IPHostEntry_IPAddressArray__get_AddressList__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Void set_AddressList(System.Net.IPAddress[])
    pub fn void__set_AddressList__1__IPAddressArray(&self, _value : &::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_void__set_AddressList__1__IPAddressArray(thrown : *mut i64, self_h : i64, _value : i64);
        }
        unsafe {
            System_Net_IPHostEntry_void__set_AddressList__1__IPAddressArray(&mut __thrown, self.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.String[] get_Aliases()
    pub fn StringArray__get_Aliases__0(&self) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_StringArray__get_Aliases__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_IPHostEntry_StringArray__get_Aliases__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Void set_Aliases(System.String[])
    pub fn void__set_Aliases__1__StringArray(&self, _value : &::System_Runtime::System::Arr<::System_Runtime::System::String>)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_void__set_Aliases__1__StringArray(thrown : *mut i64, self_h : i64, _value : i64);
        }
        unsafe {
            System_Net_IPHostEntry_void__set_Aliases__1__StringArray(&mut __thrown, self.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.String get_HostName()
    pub fn String__get_HostName__0(&self) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_String__get_HostName__0(thrown : *mut i64, self_h : i64) -> i64;
        }
        unsafe {
            let __return = SGRustObjectHandle::from_handle(System_Net_IPHostEntry_String__get_HostName__0(&mut __thrown, self.get_handle()));
            if __thrown == 0 {
                return Ok(__return);
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
    // [IsSpecialName] System.Void set_HostName(System.String)
    pub fn void__set_HostName__1__String(&self, _value : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        let mut __thrown : i64 = Default::default();
        extern {
            fn System_Net_IPHostEntry_void__set_HostName__1__String(thrown : *mut i64, self_h : i64, _value : i64);
        }
        unsafe {
            System_Net_IPHostEntry_void__set_HostName__1__String(&mut __thrown, self.get_handle(), _value.get_handle());
            if __thrown == 0 {
                return Ok(());
            } else {
                return Err(SGRustObjectHandle::from_handle(__thrown));
            }
        }
    }
}

impl Into<::System_Runtime::System::Object> for IPHostEntry {
    fn into(self) -> ::System_Runtime::System::Object {
        unsafe { ::System_Runtime::System::Object::from_handle(crate::__copy_handle(self.get_handle())) }
    }
}

pub trait System_Net_IPHostEntry_overload_IPAddressArray_get_AddressList_t_m<TA> {
    fn get_AddressList(&self, args : TA) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_get_AddressList_r_m<> {
    fn get_AddressList(&self, ) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_IPAddressArray_get_AddressList_0_m<> {
    fn get_AddressList_0(&self, ) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_void_set_AddressList_t_m<TA> {
    fn set_AddressList(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_set_AddressList_r_m<TA1> {
    fn set_AddressList(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_void_set_AddressList_1_m<TA1> {
    fn set_AddressList_1(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_StringArray_get_Aliases_t_m<TA> {
    fn get_Aliases(&self, args : TA) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_get_Aliases_r_m<> {
    fn get_Aliases(&self, ) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_StringArray_get_Aliases_0_m<> {
    fn get_Aliases_0(&self, ) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_void_set_Aliases_t_m<TA> {
    fn set_Aliases(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_set_Aliases_r_m<TA1> {
    fn set_Aliases(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_void_set_Aliases_1_m<TA1> {
    fn set_Aliases_1(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_String_get_HostName_t_m<TA> {
    fn get_HostName(&self, args : TA) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_get_HostName_r_m<> {
    fn get_HostName(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_String_get_HostName_0_m<> {
    fn get_HostName_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_void_set_HostName_t_m<TA> {
    fn set_HostName(&self, args : TA)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_set_HostName_r_m<TA1> {
    fn set_HostName(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_void_set_HostName_1_m<TA1> {
    fn set_HostName_1(&self, p1 : TA1)-> Result<(),::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_IPHostEntry_ctor_t_f<TA> {
    fn ctor(args : TA) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_ctor_r_f<> {
    fn ctor() -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_IPHostEntry_ctor_0_f<> {
    fn ctor_0() -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_AddressList_s_m<> {
    fn AddressList(&self, ) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_Aliases_s_m<> {
    fn Aliases(&self, ) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception>;
}
pub trait System_Net_IPHostEntry_overload_HostName_s_m<> {
    fn HostName(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception>;
}
impl System_Net_IPHostEntry_overload_get_AddressList_r_m<> for IPHostEntry {
    fn get_AddressList(&self, ) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        self.IPAddressArray__get_AddressList__0()
    }
}
impl System_Net_IPHostEntry_overload_IPAddressArray_get_AddressList_0_m<> for IPHostEntry {
    fn get_AddressList_0(&self, ) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        self.IPAddressArray__get_AddressList__0()
    }
}
impl System_Net_IPHostEntry_overload_IPAddressArray_get_AddressList_t_m<()> for IPHostEntry {
    fn get_AddressList(&self, _a : ()) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        self.IPAddressArray__get_AddressList__0()
    }
}
impl System_Net_IPHostEntry_overload_set_AddressList_r_m<&::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>> for IPHostEntry {
    fn set_AddressList(&self, p1 : &::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_AddressList__1__IPAddressArray(p1)
    }
}
impl System_Net_IPHostEntry_overload_void_set_AddressList_1_m<&::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>> for IPHostEntry {
    fn set_AddressList_1(&self, p1 : &::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_AddressList__1__IPAddressArray(p1)
    }
}
impl System_Net_IPHostEntry_overload_void_set_AddressList_t_m<(&::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,)> for IPHostEntry {
    fn set_AddressList(&self, a : (&::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,))-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_AddressList__1__IPAddressArray(a.0,)
    }
}
impl System_Net_IPHostEntry_overload_get_Aliases_r_m<> for IPHostEntry {
    fn get_Aliases(&self, ) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.StringArray__get_Aliases__0()
    }
}
impl System_Net_IPHostEntry_overload_StringArray_get_Aliases_0_m<> for IPHostEntry {
    fn get_Aliases_0(&self, ) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.StringArray__get_Aliases__0()
    }
}
impl System_Net_IPHostEntry_overload_StringArray_get_Aliases_t_m<()> for IPHostEntry {
    fn get_Aliases(&self, _a : ()) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.StringArray__get_Aliases__0()
    }
}
impl System_Net_IPHostEntry_overload_set_Aliases_r_m<&::System_Runtime::System::Arr<::System_Runtime::System::String>> for IPHostEntry {
    fn set_Aliases(&self, p1 : &::System_Runtime::System::Arr<::System_Runtime::System::String>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_Aliases__1__StringArray(p1)
    }
}
impl System_Net_IPHostEntry_overload_void_set_Aliases_1_m<&::System_Runtime::System::Arr<::System_Runtime::System::String>> for IPHostEntry {
    fn set_Aliases_1(&self, p1 : &::System_Runtime::System::Arr<::System_Runtime::System::String>)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_Aliases__1__StringArray(p1)
    }
}
impl System_Net_IPHostEntry_overload_void_set_Aliases_t_m<(&::System_Runtime::System::Arr<::System_Runtime::System::String>,)> for IPHostEntry {
    fn set_Aliases(&self, a : (&::System_Runtime::System::Arr<::System_Runtime::System::String>,))-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_Aliases__1__StringArray(a.0,)
    }
}
impl System_Net_IPHostEntry_overload_get_HostName_r_m<> for IPHostEntry {
    fn get_HostName(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_HostName__0()
    }
}
impl System_Net_IPHostEntry_overload_String_get_HostName_0_m<> for IPHostEntry {
    fn get_HostName_0(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_HostName__0()
    }
}
impl System_Net_IPHostEntry_overload_String_get_HostName_t_m<()> for IPHostEntry {
    fn get_HostName(&self, _a : ()) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_HostName__0()
    }
}
impl System_Net_IPHostEntry_overload_set_HostName_r_m<&::System_Runtime::System::String> for IPHostEntry {
    fn set_HostName(&self, p1 : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_HostName__1__String(p1)
    }
}
impl System_Net_IPHostEntry_overload_void_set_HostName_1_m<&::System_Runtime::System::String> for IPHostEntry {
    fn set_HostName_1(&self, p1 : &::System_Runtime::System::String)-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_HostName__1__String(p1)
    }
}
impl System_Net_IPHostEntry_overload_void_set_HostName_t_m<(&::System_Runtime::System::String,)> for IPHostEntry {
    fn set_HostName(&self, a : (&::System_Runtime::System::String,))-> Result<(),::System_Runtime::System::Exception> {
        self.void__set_HostName__1__String(a.0,)
    }
}
impl System_Net_IPHostEntry_overload_ctor_r_f<> for IPHostEntry {
    fn ctor() -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Net_IPHostEntry_overload_IPHostEntry_ctor_0_f<> for IPHostEntry {
    fn ctor_0() -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Net_IPHostEntry_overload_IPHostEntry_ctor_t_f<()> for IPHostEntry {
    fn ctor(_a : ()) -> Result<crate::System::Net::IPHostEntry,::System_Runtime::System::Exception> {
        Self::ctor__0()
    }
}
impl System_Net_IPHostEntry_overload_AddressList_s_m<> for IPHostEntry {
    fn AddressList(&self, ) -> Result<::System_Runtime::System::Arr<::System_Net_Primitives::System::Net::IPAddress>,::System_Runtime::System::Exception> {
        self.IPAddressArray__get_AddressList__0()
    }
}
impl System_Net_IPHostEntry_overload_Aliases_s_m<> for IPHostEntry {
    fn Aliases(&self, ) -> Result<::System_Runtime::System::Arr<::System_Runtime::System::String>,::System_Runtime::System::Exception> {
        self.StringArray__get_Aliases__0()
    }
}
impl System_Net_IPHostEntry_overload_HostName_s_m<> for IPHostEntry {
    fn HostName(&self, ) -> Result<::System_Runtime::System::String,::System_Runtime::System::Exception> {
        self.String__get_HostName__0()
    }
}

} // System.Net

} // System

pub mod overloads_with_count {
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginGetHostAddresses_3_f;
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginGetHostByName_3_f;
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_3_f;
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginResolve_3_f;
pub use crate::System::Net::System_Net_Dns_overload_IPAddressArray_EndGetHostAddresses_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_EndGetHostByName_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_EndGetHostEntry_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_EndResolve_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPAddressArray_GetHostAddresses_1_f;
pub use crate::System::Net::System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPAddressArray__GetHostAddressesAsync_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_GetHostByAddress_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_GetHostByName_1_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_GetHostEntry_1_f;
pub use crate::System::Net::System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_1_f;
pub use crate::System::Net::System_Net_Dns_overload_String_GetHostName_0_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_Resolve_1_f;
pub use crate::System::Net::System_Net_IPHostEntry_overload_IPAddressArray_get_AddressList_0_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_void_set_AddressList_1_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_StringArray_get_Aliases_0_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_void_set_Aliases_1_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_String_get_HostName_0_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_void_set_HostName_1_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_IPHostEntry_ctor_0_f;
}
pub mod overloads_with_tuple {
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginGetHostAddresses_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginGetHostByName_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginGetHostEntry_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IAsyncResult_BeginResolve_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPAddressArray_EndGetHostAddresses_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_EndGetHostByName_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_EndGetHostEntry_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_EndResolve_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPAddressArray_GetHostAddresses_t_f;
pub use crate::System::Net::System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPAddressArray__GetHostAddressesAsync_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_GetHostByAddress_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_GetHostByName_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_GetHostEntry_t_f;
pub use crate::System::Net::System_Net_Dns_overload_System_Threading_Tasks_Task_System_Net_IPHostEntry__GetHostEntryAsync_t_f;
pub use crate::System::Net::System_Net_Dns_overload_String_GetHostName_t_f;
pub use crate::System::Net::System_Net_Dns_overload_IPHostEntry_Resolve_t_f;
pub use crate::System::Net::System_Net_IPHostEntry_overload_IPAddressArray_get_AddressList_t_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_void_set_AddressList_t_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_StringArray_get_Aliases_t_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_void_set_Aliases_t_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_String_get_HostName_t_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_void_set_HostName_t_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_IPHostEntry_ctor_t_f;
}
pub mod overloads_special {
pub use crate::System::Net::System_Net_IPHostEntry_overload_AddressList_s_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_Aliases_s_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_HostName_s_m;
}
pub mod overloads_risky {
pub use crate::System::Net::System_Net_Dns_overload_BeginGetHostAddresses_r_f;
pub use crate::System::Net::System_Net_Dns_overload_BeginGetHostByName_r_f;
pub use crate::System::Net::System_Net_Dns_overload_BeginGetHostEntry_r_f;
pub use crate::System::Net::System_Net_Dns_overload_BeginResolve_r_f;
pub use crate::System::Net::System_Net_Dns_overload_EndGetHostAddresses_r_f;
pub use crate::System::Net::System_Net_Dns_overload_EndGetHostByName_r_f;
pub use crate::System::Net::System_Net_Dns_overload_EndGetHostEntry_r_f;
pub use crate::System::Net::System_Net_Dns_overload_EndResolve_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostAddresses_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostAddressesAsync_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostByAddress_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostByName_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostEntry_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostEntryAsync_r_f;
pub use crate::System::Net::System_Net_Dns_overload_GetHostName_r_f;
pub use crate::System::Net::System_Net_Dns_overload_Resolve_r_f;
pub use crate::System::Net::System_Net_IPHostEntry_overload_get_AddressList_r_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_set_AddressList_r_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_get_Aliases_r_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_set_Aliases_r_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_get_HostName_r_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_set_HostName_r_m;
pub use crate::System::Net::System_Net_IPHostEntry_overload_ctor_r_f;
}

