// @generated by Rustlyn.Bindings. Do not edit by hand.
#![allow(dead_code)]

unsafe extern "C" {
    fn rustlyn_bindgen_avalonia_controls_window_new(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_avalonia_controls_stack_panel_new(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_avalonia_controls_text_block_new(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_avalonia_controls_button_new(exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_avalonia_thickness_new_f64(value: f64, exception_out: *mut i32) -> i32;
    fn rustlyn_bindgen_avalonia_controls_window_set_title_utf8(
        window_handle: i32,
        title_ptr: *const u8,
        title_length: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_window_set_width_f64(
        window_handle: i32,
        width: f64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_window_set_height_f64(
        window_handle: i32,
        height: f64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_window_set_content_control(
        window_handle: i32,
        content_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_stack_panel_set_spacing_f64(
        stack_panel_handle: i32,
        spacing: f64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_stack_panel_set_margin_thickness(
        stack_panel_handle: i32,
        margin_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_panel_children_add_control(
        panel_handle: i32,
        child_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_text_block_set_text_utf8(
        text_block_handle: i32,
        text_ptr: *const u8,
        text_length: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_button_set_content_utf8(
        button_handle: i32,
        content_ptr: *const u8,
        content_length: i64,
        exception_out: *mut i32,
    ) -> i32;
    fn rustlyn_bindgen_avalonia_controls_button_subscribe_click(
        button_handle: i32,
        handler_id: i32,
        state_handle: i32,
        exception_out: *mut i32,
    ) -> i32;
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Exception {
    handle: i32,
}

impl Exception {
    fn from_handle(handle: i32) -> Result<(), Self> {
        if handle == 0 {
            Ok(())
        } else {
            Err(Self { handle })
        }
    }
}

pub trait ControlHandle {
    fn handle(&self) -> i32;
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Window {
    handle: i32,
}

impl Window {
    pub fn new() -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let handle = unsafe { rustlyn_bindgen_avalonia_controls_window_new(&mut exception_handle) };
        Exception::from_handle(exception_handle)?;
        Ok(Self { handle })
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn into_handle(self) -> i32 {
        self.handle
    }

    pub fn set_title_utf8_parts(&self, title_ptr: *const u8, title_len: i64) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_window_set_title_utf8(
                self.handle,
                title_ptr,
                title_len,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }

    pub fn set_size(&self, width: f64, height: f64) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe { rustlyn_bindgen_avalonia_controls_window_set_width_f64(self.handle, width, &mut exception_handle) };
        Exception::from_handle(exception_handle)?;
        unsafe { rustlyn_bindgen_avalonia_controls_window_set_height_f64(self.handle, height, &mut exception_handle) };
        Exception::from_handle(exception_handle)
    }

    pub fn set_content<T: ControlHandle>(&self, content: &T) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_window_set_content_control(
                self.handle,
                content.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StackPanel {
    handle: i32,
}

impl StackPanel {
    pub fn new() -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let handle = unsafe { rustlyn_bindgen_avalonia_controls_stack_panel_new(&mut exception_handle) };
        Exception::from_handle(exception_handle)?;
        Ok(Self { handle })
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn set_spacing(&self, spacing: f64) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_stack_panel_set_spacing_f64(
                self.handle,
                spacing,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }

    pub fn set_margin(&self, margin: &Thickness) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_stack_panel_set_margin_thickness(
                self.handle,
                margin.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }

    pub fn add_child<T: ControlHandle>(&self, child: &T) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_panel_children_add_control(
                self.handle,
                child.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }
}

impl ControlHandle for StackPanel {
    fn handle(&self) -> i32 {
        self.handle
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TextBlock {
    handle: i32,
}

impl TextBlock {
    pub fn new() -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let handle = unsafe { rustlyn_bindgen_avalonia_controls_text_block_new(&mut exception_handle) };
        Exception::from_handle(exception_handle)?;
        Ok(Self { handle })
    }

    pub unsafe fn from_borrowed_handle(handle: i32) -> Self {
        Self { handle }
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn set_text_utf8_parts(&self, text_ptr: *const u8, text_len: i64) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_text_block_set_text_utf8(
                self.handle,
                text_ptr,
                text_len,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }
}

impl ControlHandle for TextBlock {
    fn handle(&self) -> i32 {
        self.handle
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Button {
    handle: i32,
}

impl Button {
    pub fn new() -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let handle = unsafe { rustlyn_bindgen_avalonia_controls_button_new(&mut exception_handle) };
        Exception::from_handle(exception_handle)?;
        Ok(Self { handle })
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }

    pub fn set_content_utf8_parts(&self, content_ptr: *const u8, content_len: i64) -> Result<(), Exception> {
        let mut exception_handle = 0;
        unsafe {
            rustlyn_bindgen_avalonia_controls_button_set_content_utf8(
                self.handle,
                content_ptr,
                content_len,
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)
    }

    pub fn subscribe_click(&self, handler_id: i32, state: &TextBlock) -> Result<EventSubscription, Exception> {
        let mut exception_handle = 0;
        let handle = unsafe {
            rustlyn_bindgen_avalonia_controls_button_subscribe_click(
                self.handle,
                handler_id,
                state.handle(),
                &mut exception_handle,
            )
        };
        Exception::from_handle(exception_handle)?;
        Ok(EventSubscription { handle })
    }
}

impl ControlHandle for Button {
    fn handle(&self) -> i32 {
        self.handle
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Thickness {
    handle: i32,
}

impl Thickness {
    pub fn new(value: f64) -> Result<Self, Exception> {
        let mut exception_handle = 0;
        let handle = unsafe { rustlyn_bindgen_avalonia_thickness_new_f64(value, &mut exception_handle) };
        Exception::from_handle(exception_handle)?;
        Ok(Self { handle })
    }

    pub fn handle(&self) -> i32 {
        self.handle
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct EventSubscription {
    handle: i32,
}

impl EventSubscription {
    pub fn handle(&self) -> i32 {
        self.handle
    }
}